## Data Loading

In [270]:
import os
import numpy as np
import pandas as pd
import re
from gensim.utils import simple_preprocess
import nltk
from nltk.corpus import stopwords, words, wordnet
from nltk.stem import PorterStemmer
from bertopic import BERTopic
from gensim.models import Word2Vec

#nltk.download('stopwords')
#nltk.download('words')
#nltk.download('averaged_perceptron_tagger_eng')
#nltk.download('maxent_ne_chunker_tab')
#nltk.download('punkt_tab')

In [254]:
seed_topic_list = [['flaunt', 'reveal', 'underwear', 'sex', 'tease', 'lure', 'entice', 'flirt', 
                    'seduce', 'affair', 'adulter', 'promiscuous', 'charm', 'sexy', 'attractive', 'glamour', 
                    'ass', 'booty', 'oversexed', 'busty', 'bra', 'panty', 'lingerie', 'teddy', 'slut', 'whore', 
                    'bimbo', 'floozy', 'bitch', 'jezebel', 'mistress', 'breast', 'cleavage', 'skank', 'cougar', 
                    'temptress'], ## hypersexualizing
                    ['calculated', 'cold', 'irrational', 'hysterical', 'inhuman', 'unnatural', 'unstable', 'scheme', 
                     'fake', 'deranged', 'tears', 'cry', 'unemotional', 'uncaring', 'liar', 'manipulative', 'malinger', 
                     'uncontrollable', 'angry', 'insincere', 'empathy', 'lie', 'bitch'], ## pathologizing
                    ['bisexual', 'queer', 'bitch', 'dyke', 'butch', 'lesbian', 'gay'], ## sexuality
                    ['nurture', 'homemaker', 'virgin', 'pure', 'sacrificial', 'cold', 'uncaring', 'unfriendly', 'unemotional',
                     'abandonment', 'neglect', 'overbearing', 'selfish', 'unnatural', 'assertive', 'ugly', 'aggressive',
                     'confrontational', 'violent', 'unfeeling', 'caring', 'friendly', 'emotional', 'maternal', 
                     'feminine', 'wife', 'lady', 'woman', 'housewife'], ## gender
                    ['liar', 'lie', 'manipulative', 'unbelievable', 'exaggerate', 'unreliable', 'inconsistent', 'hysterical', 
                     'corroborate', 'atypical', 'lies'], ## discrediting
                    ['alien', 'foreign', 'backward', 'citizenship', 'wetback', 'illegal', 'dirty', 'untrustworthy', 'exotic', 
                     'diverse', 'different', 'ethnic', 'accent', 'english', 'custom', 'culture', 'steal', 'infiltrate', 'border', 'home'], ## immigration
                    ['poor', 'welfare', 'poverty', 'lazy', 'cheap', 'dirty', 'disorganized', 'messy', 'greedy', 'materialistic', 
                     'acquisitive', 'opportunity', 'trailer', 'trash'], ## poverty
                    ['drugs', 'cocaine', 'speed', 'marijuana', 'heroin', 'addict'], ## addiction
                    ['animal', 'savage', 'wolves', 'negro', 'feral', 'brute', 'angry', 'untamable', 'gang', 'lazy', 'welfare', 
                     'belligerent', 'angry', 'thug', 'community', 'dirty', 'ethnic', 'mammy'], ## racial tropes
                    ['child', 'abuse', 'neglect', 'caring', 'nurture', 'mom', 'mother', 'maternal', 'matriarch', 'dad', 'father', 
                     'paternal', 'patriarch', 'negligent'] ## parenting
                    ]

In [223]:
files = []
transcripts = []

path = '/Users/emmharv/Downloads/capitaltrialtranscripts/'
for file in os.listdir(path):

    if 'txt' in file:
        with open(path + file) as f:
            transcript = f.read()

            files.append(file)
            transcripts.append(transcript)

df = pd.DataFrame({'id' : files, 'transcript' : transcripts})

In [279]:
df['transcript_cleaned'] = df['transcript'].str.replace(r'[^a-zA-Z\s]', '', regex=True) ## remove characters other than alpha and whitespace
df['transcript_cleaned'] = df['transcript_cleaned'].str.lower() ## lowercase

stop = stopwords.words('english')
stop.extend(['q', 'question', 'mr', 'ms', 'court', 'judge', 'jury', 'testimony', 'witness', 'honor']) ## remove transcript artifacts, general trial words

df['transcript_cleaned'] = df['transcript_cleaned'].apply(simple_preprocess) ## tokenize
df['transcript_cleaned'] = df['transcript_cleaned'].apply(lambda x: [word for word in x if word not in (stop)]) ## stopwords

df['transcript_cleaned'] = df['transcript_cleaned'].apply(lambda x: [word for word in x if len(wordnet.synsets(word.lower())) > 0]) ## non-dictionary words

df.head()

,id,transcript,transcript_cleaned
0,Cynthia Coffman.txt,i 5148 THIS REQUIRES YOU TO KEEP TWO SEPARATE ...,"[requires, keep, two, separate, compartments, ..."
1,Sammantha Allen.txt,mind during the trial. Form your final opinion...,"[mind, trial, form, final, opinions, opportuni..."
2,Maureen McDermott.txt,".. ""YOU MAY NOT DISREGARD THE TESTIMONY OF THE...","[may, disregard, greater, number, witnesses, m..."
3,Brittany Holberg.txt,I Case 2:15-cv-00285-Z-BP Document 11-16 Filed...,"[case, document, filed, page, following, proce..."
4,Tiffany Cole.txt,"MR. MIZRAHI: Counsel. THE COURT: Yes, sir. MR....","[counsel, yes, sir, final, hours, carol, sumne..."

In [300]:
## Get top words to filter out if needed
all_words = df['transcript_cleaned'].explode().tolist()

fdist = nltk.FreqDist(all_words) 

top_k_words, _ = zip(*fdist.most_common(10000)) 
print(top_k_words)

('yes', 'right', 'okay', 'know', 'time', 'one', 'going', 'well', 'correct', 'think', 'like', 'go', 'sir', 'back', 'said', 'see', 'case', 'get', 'say', 'may', 'evidence', 'tell', 'first', 'want', 'two', 'remember', 'take', 'people', 'told', 'got', 'also', 'defendant', 'thank', 'believe', 'ask', 'way', 'us', 'went', 'point', 'come', 'make', 'things', 'house', 'mean', 'number', 'th', 'objection', 'yeah', 'day', 'call', 'theres', 'kind', 'look', 'let', 'person', 'asked', 'miss', 'exhibit', 'made', 'recall', 'sure', 'put', 'room', 'little', 'state', 'talking', 'actually', 'give', 'please', 'ever', 'talk', 'juror', 'really', 'came', 'left', 'area', 'fact', 'next', 'morning', 'good', 'need', 'record', 'saw', 'long', 'name', 'three', 'show', 'questions', 'page', 'around', 'death', 'part', 'even', 'another', 'much', 'happened', 'never', 'thing', 'cant', 'find', 'blood', 'years', 'heard', 'last', 'home', 'murder', 'information', 'says', 'still', 'work', 'different', 'called', 'crime', 'phone', 'children', 'statement', 'lot', 'defense', 'ill', 'read', 'saying', 'police', 'took', 'life', 'sorry', 'report', 'maybe', 'lets', 'times', 'wanted', 'use', 'present', 'photograph', 'testified', 'counsel', 'understand', 'done', 'car', 'might', 'answer', 'states', 'talked', 'nothing', 'found', 'child', 'able', 'many', 'hear', 'looking', 'detective', 'family', 'hes', 'marked', 'trying', 'probably', 'side', 'trial', 'second', 'used', 'front', 'true', 'examination', 'door', 'knew', 'either', 'mrs', 'particular', 'taken', 'thought', 'based', 'somebody', 'far', 'issue', 'seen', 'head', 'peoples', 'opinion', 'law', 'night', 'mother', 'guess', 'id', 'outside', 'body', 'clerk', 'proceedings', 'already', 'open', 'four', 'course', 'truth', 'help', 'jurors', 'object', 'defendants', 'minutes', 'asking', 'given', 'direct', 'date', 'office', 'following', 'interview', 'indicated', 'place', 'penalty', 'scene', 'matter', 'order', 'someone', 'conversation', 'money', 'reason', 'today', 'school', 'later', 'oh', 'bit', 'identification', 'tape', 'started', 'hand', 'consider', 'try', 'witnesses', 'must', 'end', 'prior', 'leave', 'together', 'telling', 'whatever', 'ahead', 'every', 'presence', 'recess', 'photographs', 'getting', 'prospective', 'couple', 'statements', 'sustained', 'whole', 'items', 'away', 'hearing', 'days', 'start', 'circumstances', 'relationship', 'stand', 'mind', 'always', 'mader', 'coming', 'kids', 'five', 'county', 'type', 'courtroom', 'period', 'move', 'inside', 'document', 'basically', 'officer', 'instructions', 'item', 'reporter', 'temple', 'gave', 'looked', 'year', 'department', 'bring', 'problem', 'testify', 'afternoon', 'pretty', 'least', 'gentlemen', 'notes', 'agree', 'aware', 'received', 'exactly', 'ladies', 'verdict', 'living', 'week', 'specific', 'involved', 'guilty', 'line', 'phase', 'instruction', 'records', 'stuff', 'jail', 'words', 'gun', 'goes', 'sort', 'contact', 'reasonable', 'feel', 'specifically', 'within', 'cause', 'care', 'keep', 'medical', 'doctor', 'top', 'working', 'overruled', 'certainly', 'hours', 'calls', 'fine', 'showing', 'certain', 'means', 'woman', 'describe', 'special', 'respect', 'kill', 'position', 'taking', 'fire', 'excuse', 'approximately', 'approach', 'though', 'degree', 'hospital', 'victim', 'held', 'old', 'sometimes', 'smith', 'break', 'close', 'met', 'november', 'tomorrow', 'terms', 'doubt', 'decision', 'picture', 'facts', 'argument', 'brought', 'test', 'form', 'mike', 'recognize', 'regarding', 'enough', 'regard', 'obviously', 'john', 'admitted', 'taylor', 'important', 'clear', 'husband', 'man', 'months', 'thornton', 'moved', 'mom', 'attorney', 'letter', 'fair', 'follows', 'making', 'happen', 'filed', 'several', 'set', 'using', 'cases', 'apartment', 'box', 'davis', 'ellison', 'stay', 'discuss', 'word', 'beyond', 'best', 'face', 'bed', 'andrew', 'speak', 'act', 'incident', 'situation', 'moment', 'factor', 'bedroom', 'six', 'dna', 'individual', 'live', 'gone', 'comes', 'hair', 'young', 'copy', 'intent', 'check', 'residence', 'process', 'mentioned', 'factors', 'earlier', 'wheeler', 'step', 'better', 'certified', 'friends', 'transcript', 'occurred', 'high', 'consistent', 'worked', 'possible', 'sworn', 'drugs', 'change', 'issues', 'job', 'attention', 'purpose', 'along', 'explain', 'hearsay', 'california', 'indicate', 'abuse', 'white', 'deputy', 'half', 'request', 'idea', 'deal', 'new', 'sitting', 'brown', 'minute', 'motion', 'problems', 'knowledge', 'daughter', 'jordan', 'lived', 'portion', 'monday', 'stop', 'april', 'previously', 'hard', 'tried', 'ago', 'courts', 'hit', 'killed', 'june', 'relevant', 'appears', 'determine', 'father', 'knife', 'recollection', 'attorneys', 'note', 'general', 'ten', 'backers', 'march', 'appear', 'described', 'green', 'july', 'exhibits', 'real', 'response', 'vehicle', 'big', 'circumstance', 'concerned', 'yesterday', 'street', 'decide', 'investigation', 'wrong', 'hour', 'expert', 'baby', 'wall', 'mental', 'behind', 'violence', 'location', 'appropriate', 'needed', 'address', 'bad', 'known', 'felt', 'excused', 'sister', 'committed', 'opportunity', 'black', 'district', 'august', 'subject', 'mc', 'small', 'october', 'early', 'seat', 'michael', 'cut', 'injuries', 'notice', 'sentence', 'bag', 'prove', 'ready', 'written', 'looks', 'floor', 'quite', 'sense', 'physical', 'bench', 'iii', 'property', 'conduct', 'aggravating', 'criminal', 'mark', 'ones', 'parents', 'pm', 'bottom', 'custody', 'mitigating', 'girl', 'wait', 'brother', 'evening', 'wife', 'memory', 'assume', 'experience', 'redirect', 'indicating', 'malone', 'pictures', 'offer', 'robinson', 'business', 'hands', 'seeing', 'shows', 'nature', 'referring', 'officers', 'investigator', 'gets', 'james', 'amount', 'count', 'crimes', 'injury', 'however', 'areas', 'understanding', 'wants', 'less', 'provided', 'cell', 'allow', 'reports', 'members', 'yet', 'code', 'month', 'standing', 'charge', 'weeks', 'actual', 'clemens', 'december', 'guilt', 'writing', 'result', 'van', 'drive', 'discussion', 'write', 'age', 'additional', 'luna', 'prosecution', 'allowed', 'usually', 'example', 'sent', 'control', 'spears', 'wrote', 'section', 'prison', 'pick', 'almost', 'seated', 'red', 'reflect', 'review', 'knows', 'thinking', 'sit', 'turn', 'rest', 'stated', 'spoke', 'search', 'great', 'effect', 'arrived', 'absolutely', 'offense', 'friend', 'occasion', 'shot', 'paper', 'personal', 'kept', 'light', 'showed', 'foundation', 'hold', 'continue', 'autopsy', 'sexual', 'numbers', 'son', 'wound', 'event', 'road', 'felony', 'training', 'telephone', 'somewhere', 'entire', 'makes', 'reading', 'friday', 'killing', 'photo', 'submit', 'supposed', 'client', 'bailiff', 'bathroom', 'force', 'documents', 'forensic', 'sergeant', 'discussed', 'monroe', 'letters', 'video', 'piece', 'parker', 'answered', 'third', 'perhaps', 'computer', 'truck', 'rob', 'disorder', 'love', 'identified', 'analysis', 'giving', 'nd', 'beginning', 'walked', 'window', 'heather', 'caused', 'veronica', 'normal', 'robbery', 'meet', 'turned', 'conclusion', 'reference', 'possibility', 'pause', 'victims', 'play', 'system', 'presented', 'wont', 'water', 'september', 'often', 'short', 'charged', 'rs', 'middleton', 'separate', 'strike', 'god', 'purposes', 'rather', 'boys', 'drug', 'full', 'familiar', 'regards', 'accurate', 'shown', 'battered', 'apparently', 'eight', 'calling', 'account', 'walk', 'examined', 'guy', 'testing', 'placed', 'basis', 'view', 'dead', 'plan', 'married', 'located', 'argue', 'become', 'sometime', 'history', 'happens', 'run', 'sheriffs', 'past', 'tells', 'david', 'chance', 'table', 'identify', 'upset', 'visit', 'follow', 'insurance', 'proof', 'testifying', 'west', 'brain', 'duly', 'condition', 'behalf', 'kitchen', 'center', 'level', 'trailer', 'available', 'behavior', 'pay', 'card', 'seven', 'longer', 'required', 'bar', 'simply', 'story', 'neck', 'listen', 'concern', 'commit', 'expect', 'list', 'january', 'brief', 'considered', 'relevance', 'sample', 'stayed', 'return', 'exact', 'raise', 'opening', 'significant', 'middle', 'lyons', 'across', 'rule', 'cross', 'virginia', 'pulled', 'guys', 'store', 'thursday', 'observed', 'appeared', 'dad', 'human', 'impact', 'reasons', 'difference', 'board', 'stopped', 'lying', 'moving', 'lunch', 'feet', 'late', 'february', 'north', 'difficult', 'attempt', 'material', 'parole', 'removed', 'hunter', 'died', 'takes', 'seems', 'according', 'individuals', 'similar', 'inmates', 'persons', 'necessarily', 'forth', 'proceed', 'blue', 'texas', 'putting', 'pattern', 'related', 'receive', 'wounds', 'possibly', 'clothes', 'wish', 'changed', 'picked', 'term', 'wade', 'prepared', 'spell', 'arrested', 'garage', 'wearing', 'provide', 'conversations', 'file', 'rossetti', 'homicide', 'support', 'crisp', 'directly', 'various', 'collected', 'refer', 'bullet', 'voice', 'parties', 'speculation', 'tuesday', 'send', 'needs', 'necessary', 'decided', 'methamphetamine', 'generally', 'service', 'pass', 'common', 'weight', 'concerning', 'legal', 'clearly', 'nine', 'leading', 'became', 'personality', 'heart', 'marks', 'requested', 'sex', 'women', 'interviewed', 'unit', 'alone', 'group', 'theory', 'food', 'attempted', 'offered', 'large', 'submitted', 'conrad', 'immediately', 'alleged', 'female', 'party', 'enforcement', 'pull', 'lady', 'punishment', 'tests', 'including', 'paragraph', 'arm', 'city', 'running', 'finding', 'finish', 'none', 'pain', 'throughout', 'ruling', 'speaking', 'entered', 'watch', 'stain', 'background', 'except', 'samples', 'signed', 'driving', 'employed', 'corner', 'diagram', 'convicted', 'williams', 'lie', 'lines', 'shirt', 'lee', 'seemed', 'finally', 'walking', 'results', 'missing', 'commission', 'ability', 'played', 'seem', 'final', 'resumed', 'lack', 'clothing', 'allen', 'patient', 'church', 'near', 'wednesday', 'acts', 'meaning', 'spent', 'book', 'likely', 'pages', 'afraid', 'envelope', 'paid', 'opened', 'photos', 'happy', 'swanson', 'girls', 'forward', 'events', 'direction', 'arguments', 'pointing', 'reed', 'reviewed', 'policy', 'alcohol', 'station', 'personally', 'knowing', 'nobody', 'apply', 'hurt', 'skin', 'starting', 'initially', 'language', 'folks', 'capital', 'express', 'begin', 'burn', 'soon', 'building', 'closet', 'born', 'essentially', 'ii', 'tiffany', 'complete', 'percent', 'print', 'meeting', 'unusual', 'began', 'adams', 'detectives', 'standard', 'depicted', 'gotten', 'normally', 'nice', 'holding', 'emotional', 'comment', 'free', 'addition', 'value', 'company', 'extent', 'motel', 'objections', 'referred', 'indicates', 'completely', 'crying', 'returned', 'original', 'health', 'warrant', 'sign', 'lab', 'brooke', 'touch', 'continued', 'leaving', 'screen', 'deliberations', 'meant', 'nelson', 'included', 'clean', 'weapon', 'activity', 'contained', 'hallway', 'intend', 'social', 'briefly', 'entitled', 'drove', 'assuming', 'park', 'believed', 'bank', 'pregnant', 'mouth', 'inmate', 'interviews', 'opinions', 'starts', 'treatment', 'dark', 'names', 'inconsistent', 'conference', 'determination', 'weekend', 'kidnapping', 'introduced', 'character', 'profile', 'trauma', 'examine', 'reported', 'diagnosis', 'die', 'trouble', 'fairly', 'multiple', 'previous', 'hope', 'plastic', 'respond', 'older', 'limited', 'discovery', 'mitigation', 'irrelevant', 'ways', 'feeling', 'walker', 'intended', 'apologize', 'ran', 'vague', 'single', 'raised', 'prints', 'harrison', 'official', 'kinds', 'field', 'remain', 'initial', 'matters', 'include', 'figure', 'context', 'thomas', 'agreed', 'marshall', 'penal', 'occasions', 'admit', 'instance', 'playing', 'serious', 'affect', 'men', 'noticed', 'anyway', 'duty', 'closing', 'sat', 'especially', 'appreciate', 'proved', 'security', 'spend', 'mention', 'types', 'eye', 'observe', 'manner', 'cherry', 'color', 'boy', 'refresh', 'angry', 'impression', 'sides', 'eventually', 'male', 'handle', 'eyes', 'happening', 'ground', 'lost', 'violent', 'foot', 'closed', 'leon', 'somehow', 'symptoms', 'proper', 'pending', 'otherwise', 'services', 'loved', 'doc', 'suggest', 'whos', 'due', 'frame', 'accept', 'anywhere', 'learned', 'ray', 'assault', 'occur', 'introduce', 'size', 'solemnly', 'shoes', 'scott', 'ultimately', 'tv', 'major', 'points', 'practice', 'inches', 'add', 'sleep', 'laboratory', 'positive', 'stains', 'public', 'consideration', 'research', 'circumstantial', 'la', 'sounds', 'damage', 'martin', 'influence', 'particularly', 'shed', 'rebuttal', 'somewhat', 'dealing', 'lorraine', 'cole', 'inquire', 'bill', 'psychological', 'parts', 'fear', 'curry', 'albert', 'devon', 'closer', 'responsibility', 'assist', 'assigned', 'stipulation', 'sufficient', 'latent', 'pieces', 'lower', 'world', 'till', 'listed', 'total', 'learn', 'charges', 'contents', 'wed', 'twice', 'investigators', 'program', 'session', 'ended', 'noted', 'repeat', 'rich', 'handwriting', 'draw', 'covered', 'dates', 'email', 'sound', 'smoke', 'buy', 'copies', 'connection', 'jr', 'arizona', 'gives', 'lead', 'answers', 'comments', 'swear', 'lives', 'straight', 'prosecutor', 'seconds', 'hall', 'talks', 'findings', 'scared', 'robert', 'stress', 'forms', 'richards', 'microphone', 'deliberate', 'spatter', 'cover', 'substance', 'responsible', 'graham', 'fingerprints', 'fight', 'domestic', 'entry', 'juries', 'member', 'feelings', 'elements', 'physically', 'lay', 'tapes', 'independent', 'christopher', 'instead', 'violation', 'signature', 'evaluation', 'understood', 'named', 'anymore', 'collect', 'arrest', 'jonathan', 'cynthia', 'therefore', 'sheet', 'trip', 'instructed', 'fall', 'carolina', 'keaton', 'agreement', 'oath', 'recording', 'relates', 'message', 'recovered', 'quote', 'marriage', 'places', 'admissible', 'conviction', 'waiting', 'noon', 'lawyer', 'suspect', 'glass', 'alternates', 'doctors', 'malachi', 'college', 'details', 'procedure', 'willing', 'purse', 'bruises', 'chart', 'rules', 'checks', 'explained', 'action', 'data', 'description', 'burden', 'depending', 'burned', 'quickly', 'passed', 'moore', 'depends', 'frank', 'potential', 'finished', 'admission', 'alive', 'laying', 'douglas', 'detail', 'community', 'interest', 'justice', 'parking', 'admonition', 'underneath', 'heres', 'probation', 'broken', 'contacted', 'tested', 'beat', 'johnson', 'access', 'questioned', 'instruct', 'gloves', 'experts', 'conclude', 'power', 'reach', 'burglary', 'watching', 'disregard', 'source', 'herb', 'shower', 'motive', 'mason', 'national', 'hundred', 'surface', 'gunshot', 'indication', 'safe', 'preliminary', 'judgment', 'mad', 'pointed', 'funk', 'aunt', 'staying', 'trash', 'sunday', 'permission', 'brewer', 'mothers', 'questioning', 'acting', 'imagine', 'dated', 'ring', 'shell', 'regular', 'aggravation', 'branch', 'possession', 'woods', 'arms', 'inaudible', 'denied', 'minor', 'compare', 'eat', 'recorded', 'birthday', 'dog', 'range', 'christmas', 'sic', 'series', 'foreperson', 'length', 'doors', 'nurse', 'shoe', 'deliberation', 'surgery', 'conclusions', 'syndrome', 'facility', 'acted', 'works', 'alternate', 'credit', 'checked', 'stricken', 'skull', 'jones', 'dinner', 'jackson', 'credibility', 'estimate', 'chair', 'completed', 'license', 'duties', 'substantial', 'master', 'clinical', 'pants', 'scope', 'hole', 'christie', 'helped', 'lawyers', 'accomplice', 'jensen', 'gas', 'malice', 'mine', 'comparison', 'agent', 'grade', 'ordered', 'transcripts', 'medication', 'typically', 'main', 'associated', 'fit', 'team', 'quick', 'obtained', 'south', 'emergency', 'chest', 'university', 'key', 'accurately', 'upper', 'torture', 'divorce', 'opposed', 'manager', 'rushing', 'patients', 'observations', 'definition', 'realize', 'adult', 'rephrase', 'strong', 'totally', 'air', 'abused', 'verdicts', 'camera', 'involving', 'withdraw', 'firearm', 'resume', 'saturday', 'discussing', 'low', 'staff', 'hot', 'leg', 'focus', 'future', 'town', 'definitely', 'belt', 'threat', 'riverside', 'bought', 'stomach', 'explanation', 'depression', 'fired', 'conducted', 'cards', 'obvious', 'sheriff', 'shortly', 'post', 'require', 'clock', 'da', 'relate', 'carpet', 'pardon', 'arguing', 'text', 'protect', 'locked', 'class', 'ha', 'conspiracy', 'finger', 'pillow', 'treated', 'planning', 'boyfriend', 'media', 'reid', 'distance', 'birth', 'numerous', 'spoken', 'mail', 'duct', 'released', 'childhood', 'hitting', 'scale', 'swab', 'lesser', 'trunk', 'proven', 'news', 'enter', 'twelve', 'setting', 'actions', 'natural', 'loss', 'rely', 'attached', 'changes', 'financial', 'clark', 'led', 'rights', 'hang', 'sick', 'stab', 'exception', 'interpretation', 'drop', 'murders', 'establish', 'couch', 'hotel', 'cummings', 'choice', 'parked', 'jacket', 'east', 'pressure', 'oklahoma', 'papers', 'laid', 'depict', 'role', 'lake', 'grandmother', 'walton', 'upstairs', 'remove', 'reaction', 'assessment', 'vanessa', 'vote', 'allegation', 'mary', 'jimmy', 'al', 'receipt', 'concerns', 'driveway', 'dropped', 'fingerprint', 'funeral', 'wanting', 'fill', 'correctly', 'schedule', 'currently', 'originally', 'andrews', 'fourth', 'books', 'videotape', 'demeanor', 'dalton', 'washington', 'version', 'reporting', 'easy', 'liked', 'bringing', 'kid', 'drivers', 'gentleman', 'partner', 'yelling', 'besides', 'education', 'risk', 'application', 'match', 'summer', 'wright', 'negative', 'orange', 'yard', 'broke', 'examiner', 'guns', 'suicide', 'simple', 'determined', 'study', 'comfortable', 'younger', 'todd', 'cash', 'subpoena', 'relating', 'reagan', 'bleeding', 'leaves', 'yellow', 'facing', 'prejudicial', 'counts', 'becomes', 'daily', 'plus', 'carry', 'shooting', 'professional', 'chief', 'appearance', 'lied', 'bunk', 'restaurant', 'brothers', 'requires', 'fashion', 'effort', 'bruising', 'kentucky', 'extreme', 'bunch', 'communication', 'sentencing', 'severe', 'performed', 'listening', 'significance', 'forget', 'legs', 'drinking', 'concluded', 'mobile', 'belief', 'reached', 'hill', 'gate', 'engaged', 'sealed', 'disagree', 'accident', 'determining', 'attack', 'studies', 'caught', 'sustain', 'lose', 'ride', 'desk', 'cps', 'complies', 'testifies', 'screaming', 'interesting', 'arrive', 'followed', 'kennedy', 'bradbury', 'fast', 'hell', 'pathology', 'exist', 'extremely', 'element', 'perform', 'remorse', 'drink', 'proceeding', 'base', 'television', 'gain', 'wear', 'population', 'environment', 'benefit', 'improper', 'miller', 'clarify', 'traumatic', 'advised', 'portions', 'dire', 'fell', 'tub', 'inch', 'fbi', 'shoulder', 'created', 'complex', 'grabbed', 'hanging', 'remind', 'interested', 'continuing', 'cells', 'judicial', 'blanket', 'rape', 'private', 'medicine', 'characteristics', 'whatsoever', 'transfer', 'filled', 'uncle', 'neither', 'obtain', 'easier', 'stick', 'towel', 'row', 'package', 'safety', 'blow', 'prepare', 'locations', 'developed', 'murdered', 'beating', 'worse', 'causing', 'proposed', 'volume', 'sisters', 'paying', 'rooms', 'joseph', 'instrument', 'superior', 'capacity', 'alabama', 'handed', 'labeled', 'pool', 'wi', 'moral', 'causes', 'keys', 'fake', 'chase', 'false', 'steps', 'intentionally', 'cars', 'smaller', 'baker', 'describing', 'united', 'machine', 'cord', 'honest', 'claim', 'presentation', 'offering', 'throw', 'marker', 'absence', 'sympathy', 'jewelry', 'metal', 'shift', 'image', 'responded', 'article', 'pursuant', 'grounds', 'thanks', 'circle', 'lights', 'premeditation', 'cold', 'difficulty', 'clients', 'psychiatric', 'frequently', 'suggested', 'struck', 'cocaine', 'tend', 'primarily', 'signs', 'touched', 'authority', 'stage', 'avoid', 'drawing', 'supreme', 'primary', 'failure', 'bell', 'loud', 'informed', 'activities', 'inquiry', 'effects', 'chose', 'stipulate', 'objecting', 'choose', 'applies', 'discussions', 'deliberating', 'permitted', 'tied', 'psychologist', 'fifth', 'lots', 'suffering', 'society', 'average', 'aspect', 'listened', 'speed', 'passenger', 'function', 'parent', 'helping', 'tissue', 'trust', 'deputies', 'offenses', 'deciding', 'unable', 'established', 'lies', 'plea', 'neighborhood', 'federal', 'downstairs', 'evans', 'sleeping', 'donna', 'track', 'incidents', 'motions', 'bus', 'plans', 'fifteen', 'aid', 'womans', 'apart', 'jurys', 'harm', 'probative', 'worker', 'mostly

In [ ]:
## these are mostly court/common words and names that were messing up my modeling due to appearing everywhere
common = ['yes', 'right', 'would', 'okay', 'know', 'time', 'thats', 'dont', 'one', 'going', 'well', 'correct', 'think', 'im', 'like', 
          'go', 'sir', 'back', 'said', 'see', 'case', 'get', 'didnt', 'say', 'may', 'evidence', 'could', 'tell', 'first', 'want', 'two', 
          'remember', 'take', 'people', 'told', 'got', 'also', 'defendant', 'thank', 'anything', 'believe', 'ask', 'something', 'youre', 
          'way', 'us', 'went', 'point', 'come', 'make', 'things', 'mean', 'number', 'th', 'objection', 'yeah', 'day', 'call', 
          'theres', 'kind', 'whether', 'look', 'let', 'person', 'asked', 'miss', 'exhibit', 'made', 'recall', 'sure', 'put', 
          'state', 'talking', 'actually', 'give', 'please', 'shes', 'ever', 'talk', 'juror', 'really', 'came', 'left', 'area', 
          'fact', 'next', 'morning', 'good', 'need', 'record', 'saw', 'long', 'name', 'three', 'show', 'questions', 'page', 'around', 
          'part', 'even', 'dr', 'another', 'much', 'happened', 'never', 'thing', 'cant', 'find', 'wasnt', 'years', 'heard', 'last', 
          'information', 'says', 'still', 'different', 'called', 'phone', 'statement', 'lot', 'defense', 'ill', 'read', 'saying',
          'farley', 'took', 'else', 'report', 'maybe', 'lets', 'maam', 'times', 'wanted', 'use', 'present', 'photograph', 'testified', 
          'counsel', 'understand', 'done', 'might', 'answer', 'states', 'doesnt', 'talked', 'nothing', 'found', 'able', 'many', 'hear', 
          'looking', 'detective', 'hes', 'whats', 'marked', 'trying', 'probably', 'side', 'trial', 'second', 'used', 'front', 'true', 
          'examination', 'door', 'theyre', 'knew', 'rushton', 'either', 'ive', 'youve', 'uh', 'mrs', 'particular', 'taken', 'thought', 
          'based', 'somebody', 'far', 'issue', 'seen', 'head', 'peoples', 'opinion', 'law', 'guess', 'id', 'clerk', 'proceedings', 
          'already', 'open', 'four', 'course', 'help', 'jurors', 'object', 'defendants', 'minutes', 'asking', 'given', 'direct', 
          'date', 'office', 'following', 'interview', 'indicated', 'place', 'penalty', 'scene', 'matter', 'order', 'someone', 
          'conversation', 'reason', 'today', 'later', 'oh', 'bit', 'identification', 'tape', 'started', 'hand', 'consider', 'try', 
          'witnesses', 'must', 'end', 'prior', 'leave', 'together', 'without', 'telling', 'whatever', 'ahead', 'every', 'presence', 
          'recess', 'photographs', 'wouldnt', 'getting', 'prospective', 'couple', 'isnt', 'statements', 'sustained', 'whole', 'items', 
          'away', 'hearing', 'everything', 'days', 'start', 'circumstances', 'stand', 'mind', 'always', 'mader', 'coming', 'five', 'county', 
          'type', 'courtroom', 'period', 'move', 'inside', 'document', 'basically', 'officer', 'instructions', 'item', 'reporter', 'gave', 
          'looked', 'year', 'department', 'bring', 'problem', 'testify', 'afternoon', 'pretty', 'least', 'gentlemen', 'notes', 'agree', 
          'caro', 'aware', 'since', 'received', 'exactly', 'ladies', 'verdict', 'living', 'couldnt', 'week', 'specific', 'involved', 
          'line', 'phase', 'instruction', 'records', 'stuff', 'ingber', 'words', 'anybody', 'goes', 'sort', 'contact', 'reasonable', 
          'feel', 'specifically', 'within', 'cause', 'keep', 'top', 'uhhuh', 'overruled', 'marlow', 'certainly', 'hours', 'calls', 
          'fine', 'showing', 'certain', 'means', 'haight', 'describe', 'special', 'position', 'taking', 'excuse', 'approximately', 
          'approach', 'though', 'degree', 'held', 'upon', 'sometimes', 'smith', 'close', 'met', 'november', 'tomorrow', 'terms', 
          'decision', 'picture', 'facts', 'goldstein', 'argument', 'brought', 'test', 'csr', 'form', 'mike', 'recognize', 'regarding', 
          'enough', 'regard', 'obviously', 'john', 'admitted', 'taylor', 'important', 'clear', 'months', 'thornton', 'moved', 'attorney', 
          'letter', 'fair', 'follows', 'making', 'happen', 'weve', 'filed', 'anyone', 'several', 'coffman', 'set', 'using', 'cases', 'davis', 
          'ellison', 'stay', 'discuss', 'word', 'beyond', 'best', 'andrew', 'speak', 'act', 'incident', 'situation', 'moment', 'factor', 'six', 
          'rpr', 'individual', 'comes', 'copy', 'intent', 'check', 'process', 'gonzales', 'mentioned', 'factors', 'earlier', 'wheeler', 'step', 
          'better', 'martinez', 'certified', 'belter', 'transcript', 'occurred', 'consistent', 'possible', 'sworn', 'change', 'issues', 
          'attention', 'purpose', 'along', 'explain', 'hearsay', 'california', 'indicate', 'deputy', 'request', 'idea', 'deal', 'ivan', 
          'new', 'craig', 'sitting', 'minute', 'motion', 'knowledge', 'jordan', 'lived', 'portion', 'monday', 'stop', 'april', 'michelle', 
          'previously', 'hard', 'tried', 'burkow', 'ago', 'whereupon', 'courts', 'aki', 'june', 'youll', 'relevant', 'appears', 'determine', 
          'recollection', 'attorneys', 'note', 'general', 'ten', 'backers', 'march', 'appear', 'described', 'green', 'july', 'exhibits', 'real', 
          'response', 'werent', 'vehicle', 'big', 'circumstance', 'yesterday', 'street', 'decide', 'everybody', 'investigation', 'hour', 
          'expert', 'behind', 'st', 'location', 'needed', 'takasugi', 'address', 'excused', 'havent', 'committed', 'opportunity', 'district', 
          'august', 'althaus', 'subject', 'mc', 'small', 'october', 'traci', 'early', 'seat', 'michael', 'notice', 'sentence', 'bag', 'prove',
          'ready', 'written', 'looks', 'floor', 'quite', 'sense', 'physical', 'bench', 'iii', 'property', 'conduct', 'bingham', 
          'mark', 'ones', 'patterson', 'miskovsky', 'pm', 'bottom', 'snyder', 'wait', 'evening', 'assume', 'experience', 'redirect', 
          'indicating', 'brenda', 'malone', 'pictures', 'yall', 'offer', 'robinson', 'seeing', 'shows', 
          'referring', 'officers', 'investigator', 'gets', 'james', 'amount', 'count', 'however', 'areas', 'understanding', 'wants', 
          'less', 'provided', 'cell', 'allow', 'unless', 'reports', 'members', 'yet', 'code', 'month', 'standing', 'charge', 'weeks', 
          'actual', 'clemens', 'december', 'guilt', 'cannot', 'writing', 'oclock', 'result', 'versus', 'towards', 'discussion', 'write', 
          'additional', 'luna', 'prosecution', 'scalisi', 'allowed', 'usually', 'example', 'sent', 'control', 'wrote', 'section', 'prison', 
          'pick', 'almost', 'seated', 'reflect', 'review', 'knows', 'thinking', 'sit', 'turn', 'rest', 'stated', 'spoke', 'search', 'great', 
          'effect', 'arrived', 'absolutely', 'occasion', 'paper', 'kept', 'light', 'showed', 'foundation', 'hold', 'continue', 'autopsy', 
          'numbers', 'dermott', 'event', 'telephone', 'somewhere', 'entire', 'makes', 'reading', 'friday', 'photo', 'submit', 
          'client', 'bailiff', 'bathroom', 'documents', 'cathy', 'forensic', 'sergeant', 'discussed', 'monroe', 'letters', 'video', 'piece', 
          'parker', 'answered', 'third', 'perhaps', 'rob', 'identified', 'analysis', 'giving', 'nd', 'beginning', 'walked', 'window', 'heather', 
          'etezadi', 'caused', 'veronica', 'okunwiese', 'meet', 'turned', 'conclusion', 'reference', 'possibility', 'pause', 'play', 'system', 
          'presented', 'wont', 'popkins', 'water', 'september', 'often', 'short', 'charged', 'rs', 'middleton', 'separate',  'purposes', 
          'rather', 'mccracken', 'full', 'exum', 'familiar', 'regards', 'accurate', 'shown', 'apparently', 'eight', 'joe', 'calling', 
          'kouch', 'account', 'walk', 'examined', 'testing', 'placed', 'basis', 'view', 'plan', 'located', 'become', 'sometime', 
          'happens', 'run', 'sheriffs', 'past', 'tells', 'david', 'chance', 'table', 'identify', 'visit', 'follow', 'proof', 'testifying', 
          'west', 'duly', 'behalf', 'center', 'level', 'available', 'shall', 'behavior', 'pay', 'card', 'seven', 'raul', 'lafferty', 'longer',
          'required', 'simply', 'story', 'neck', 'listen', 'concern', 'commit', 'expect', 'list', 'greg', 'january', 'others', 'brief', 
          'considered', 'relevance', 'sample', 'san', 'stayed', 'genny', 'return', 'exact', 'balleste', 'raise', 'opening', 'significant', 
          'middle', 'lyons', 'across', 'rule', 'cross', 'virginia', 'pulled', 'store', 'thursday', 'observed', 'appeared', 'impact', 'reasons', 
          'gieger', 'calhoun', 'difference', 'board', 'lunch', 'feet', 'late', 'february', 'wendi', 'north', 'difficult', 'howardregan', 
          'attempt', 'material', 'parole', 'removed', 'rd', 'hunter', 'takes', 'seems', 'according', 'individuals', 'similar', 'inmates', 
          'persons', 'markson', 'necessarily', 'forth', 'proceed', 'blue', 'texas', 'putting', 'pattern', 'related', 'receive', 'possibly', 
          'changed', 'picked', 'ciraolo', 'term', 'wade', 'prepared', 'spell', 'arrested', 'garage', 'provide', 'conversations', 'file', 
          'rossetti', 'support', 'crisp', 'directly', 'various', 'collected', 'refer', 'voice', 'parties', 'speculation', 'tuesday', 'send', 
          'needs', 'necessary', 'decided', 'generally', 'service', 'pass', 'common', 'concerning', 'legal', 'clearly', 'nine', 'caudill', 
          'leading', 'became', 'personality', 'requested', 'interviewed', 'unit', 'alone', 'group', 'theory', 'attempted', 'offered', 'large', 
          'submitted', 'everyone', 'conrad', 'ricky', 'immediately', 'party', 'enforcement', 'pull', 'tests', 'including', 'paragraph', 
          'macher', 'landon', 'city', 'running', 'finding', 'finish', 'none', 'throughout', 'ruling', 'speaking', 'entered', 'watch', 
          'background', 'although', 'except', 'samples', 'signed', 'corner', 'diagram', 'convicted', 'williams', 'lines', 'shirt', 'lee', 
          'seemed', 'finally', 'walking', 'results', 'missing', 'commission', 'sarinana', 'ability', 'played', 'seem', 'cindy', 'final', 
          'resumed', 'youd', 'lack', 'allen', 'patient', 'near', 'wednesday', 'acts', 'meaning', 'spent', 'likely', 'opened', 'photos', 
          'lisa', 'dusek', 'swanson', 'forward', 'events', 'narine', 'direction', 'pointing', 'garcia', 'reed', 'reviewed', 'policy', 
          'station', 'personally', 'knowing', 'nobody', 'apply', 'starting', 'initially', 'folks', 'capital', 'express', 'begin', 
          'soon', 'building', 'essentially', 'ii', 'tiffany', 'complete', 'percent', 'print', 'meeting', 'unusual', 'began', 'adams', 
          'detectives', 'standard', 'chris', 'depicted', 'rosie', 'gotten', 'normally', 'holding', 'comment', 'addition', 'harrelson', 
          'michaud', 'extent', 'objections', 'referred', 'indicates', 'completely', 'returned', 'original', 'warrant', 'sign', 'janeen', 
          'lab', 'brooke', 'continued', 'leaving', 'screen', 'deliberations', 'meant', 'nelson', 'included', 'activity', 'contained', 
          'hallway', 'intend', 'social', 'briefly', 'cargill', 'assuming', 'park', 'believed', 'bank', 'inmate', 'interviews', 
          'opinions', 'starts', 'treatment', 'dark', 'names', 'inconsistent', 'conference', 'arent', 'determination', 'weekend',
          'introduced', 'character', 'profile', 'examine', 'reported', 'karl', 'fairly', 'multiple', 'previous', 'respond', 'limited', 
          'discovery', 'mitigation', 'irrelevant', 'ways', 'walker', 'intended', 'apologize', 'ran', 'andriano', 'vague', 'single', 
          'raised', 'prints', 'harrison', 'official', 'kinds', 'field', 'remain', 'initial', 'eldridge', 'hadnt', 'matters', 'include', 
          'figure', 'context', 'thomas', 'agreed', 'daveggio', 'marshall', 'penal', 'occasions', 'admit', 'instance', 'um', 'serious', 
          'affect', 'noticed', 'anyway', 'closing', 'sat', 'especially', 'appreciate', 'proved', 'security', 'spend', 'mention', 'types', 
          'observe', 'manner', 'refresh', 'impression', 'sides', 'eventually', 'handle', 'happening', 'closed', 'leon', 'somehow', 'proper', 
          'pending', 'otherwise', 'services', 'shawna', 'theyve', 'doc', 'larson', 'suggest', 'richard', 'whos', 'due', 'whose', 'ame', 
          'accept', 'anywhere', 'learned', 'ray', 'occur', 'introduce', 'toward', 'size', 'pageid', 'solemnly', 'scott', 'ultimately', 
          'major', 'points', 'practice', 'inches', 'add', 'laboratory', 'positive', 'consideration', 'research', 'circumstantial', 'la', 
          'sortino', 'sounds', 'martin', 'particularly', 'shed', 'rebuttal', 'somewhat', 'lorraine', 'susan', 'cole', 'cvdcreba', 
          'inquire', 'bill', 'psychological', 'goforth', 'parts', 'curry', 'albert', 'devon', 'closer', 'assist', 'assigned', 
          'pavatt', 'morreale', 'stipulation', 'sufficient', 'latent', 'pieces', 'neal', 'steve', 'lower', 'world', 'till', 'listed', 
          'total', 'learn', 'charges', 'contents', 'twice', 'investigators', 'program', 'session', 'ended', 'noted', 'repeat', 'rich', 
          'hey', 'handwriting', 'ah', 'draw', 'covered', 'dates', 'email', 'sound', 'buy', 'copies', 'connection', 'marvin', 'jr', 
          'arizona', 'gives', 'gallagher', 'lead', 'answers', 'comments', 'swear', 'lives', 'straight', 'prosecutor', 'seconds', 'hall', 
          'talks', 'whenever', 'findings', 'magana', 'robert', 'forms', 'richards', 'microphone', 'deliberate', 'cover', 'graham', 
          'fingerprints', 'mulder', 'entry', 'juries', 'member', 'elements', 'lay', 'tapes', 'independent', 'christopher', 'instead', 
          'tuten', 'signature', 'valerie', 'evaluation', 'understood', 'named', 'anymore', 'collect', 'deblase', 'arrest', 'jonathan', 
          'cynthia', 'therefore', 'sheet', 'trip', 'instructed', 'carolina', 'keaton', 'agreement', 'oath', 'recording', 'relates', 
          'message', 'recovered', 'quote', 'places', 'admissible', 'conviction', 'waiting', 'di', 'noon', 'lawyer', 'suspect', 'glass', 
          'alternates', 'doctors', 'malachi', 'college', 'details', 'procedure', 'willing', 'chart', 'rules', 'checks', 'explained', 
          'action', 'data', 'description', 'depending', 'quickly', 'passed', 'moore', 'kim', 'depends', 'frank', 'finished', 
          'admission', 'douglas', 'detail', 'community', 'interest', 'justice', 'parking', 'admonition', 'underneath', 'heres', 
          'probation', 'contacted', 'tested', 'johnson', 'access', 'questioned', 'instruct', 'gloves', 'experts', 'conclude',
          'reach', 'watching', 'shouldnt', 'disregard', 'source', 'shower', 'motive', 'mason', 'national', 'hundred', 'surface', 
          'indication', 'preliminary', 'judgment', 'pointed', 'staying', 'sunday', 'permission', 'onto', 'brewer', 'raymond', 
          'questioning', 'imagine', 'regular', 'branch', 'possession', 'inaudible', 'denied', 'per', 'compare', 'recorded', 'curran', 
          'range', 'christmas', 'sic', 'series', 'foreperson', 'length', 'doors', 'nurse', 'shoe', 'deliberation', 'conclusions',
          'works', 'alternate', 'haas', 'strellis', 'credit', 'checked', 'jones', 'dinner', 'jackson', 'estimate', 'chair', 'houchin', 
          'darlie', 'completed', 'license', 'duties', 'substantial', 'master', 'clinical', 'pants', 'scope', 'hole', 'christie', 'helped', 
          'lawyers', 'accomplice', 'jensen', 'gas', 'mine', 'comparison', 'agent', 'grade', 'cvzbp', 'ordered', 'transcripts', 'typically', 
          'rottiers', 'main', 'associated', 'fit', 'team', 'quick', 'obtained', 'south', 'emergency', 'forde', 'routier', 'key', 'accurately',
          'upper', 'opposed', 'rushing', 'patients', 'observations', 'definition', 'realize', 'rephrase', 'strong', 'totally', 'rafael', 
          'verdicts', 'camera', 'involving', 'withdraw', 'resume', 'saturday', 'discussing', 'low', 'staff', 'focus', 'future', 'town', 
          'definitely', 'berger', 'riverside', 'bought', 'explanation', 'hasnt', 'sabatino', 'mosty', 'conducted', 'sheriff', 'shortly', 
          'post', 'require', 'clock', 'da', 'relate', 'pardon', 'text', 'protect', 'locked', 'class', 'caros', 'ha',
          'treated', 'planning', 'media', 'reid', 'distance', 'numerous', 'spoken', 'mail', 'released', 'scale', 'swab', 'lesser', 
          'proven', 'news', 'enter', 'twelve', 'setting', 'actions', 'natural', 'loss', 'rely', 'attached', 'weiher', 'changes',
          'clark', 'led', 'rights', 'hang', 'delozier', 'exception', 'interpretation', 'drop', 'establish', 'alfaro', 'cummings', 'choice', 
          'parked', 'east', 'pressure', 'oklahoma', 'eubanks', 'papers', 'laid', 'depict', 'role', 'walton', 'upstairs', 'remove', 'reaction', 
          'assessment', 'vanessa', 'vote', 'allegation', 'ccr', 'mary', 'jimmy', 'al', 'linda', 'receipt', 'concerns', 'driveway', 'mcentire', 
          'dropped', 'steven', 'fingerprint', 'beeson', 'andor', 'funeral', 'wanting', 'fill', 'correctly', 'schedule', 'currently', 'among', 
          'originally', 'andrews', 'fourth', 'books', 'videotape', 'demeanor', 'dalton', 'washington', 'version', 'reporting', 'easy', 'liked', 
          'bringing', 'drivers', 'brandon', 'gentleman', 'rodriguez', 'partner', 'los', 'yelling', 'besides', 'education', 'risk', 'application', 
          'match', 'summer', 'wright', 'examiner', 'simple', 'determined', 'study', 'comfortable', 'younger', 'manling', 'todd', 'subpoena', 
          'relating', 'reagan', 'facing', 'prejudicial', 'counts', 'becomes', 'daily', 'plus', 'carry', 'professional', 'chief', 'appearance', 
          'alvarez', 'requires', 'effort', 'kentucky', 'extreme', 'bunch', 'communication', 'sentencing', 'performed', 'listening', 'significance', 
          'carrington', 'forget', 'meacham', 'concluded', 'mobile', 'belief', 'reached', 'sealed', 'disagree', 'accident', 'riehl', 
          'determining', 'caught', 'sustain', 'lose', 'ride', 'william', 'desk', 'cps', 'complies', 'testifies', 'interesting', 'arrive', 
          'followed', 'kennedy', 'bradbury', 'fast', 'hell', 'jim', 'exist', 'extremely', 'element', 'flores', 'proceeding', 'base', 
          'gain', 'wear', 'jeremy', 'hed', 'population', 'benefit', 'improper', 'tina', 'miller', 'clarify', 'advised', 'portions', 
          'voir', 'dire', 'fell', 'tub', 'inch', 'fbi', 'shoulder', 'blanche', 'created', 'complex', 'grabbed', 'hanging', 'remind', 'interested', 
          'continuing', 'cells', 'judicial', 'blanket', 'private', 'characteristics', 'whatsoever', 'transfer', 'filled', 'neither', 'obtain', 
          'easier', 'stick', 'crabtree', 'towel', 'row', 'prepare', 'locations', 'developed', 'omar', 'worse', 'causing', 'firetag', 'proposed', 
          'volume', 'paying', 'rooms', 'joseph', 'instrument', 'superior', 'capacity', 'alabama', 'handed', 'labeled', 'pool', 'wi',
          'causes', 'larsen', 'keys', 'joey', 'fake', 'chase', 'false', 'briuana', 'steps', 'intentionally', 'cars', 'smaller', 'baker']

df['transcript_cleaned'] = df['transcript_cleaned'].apply(lambda x: [word for word in x if word not in (common)]) ## common words

In [172]:
## removing some proper nouns id'ed during topic modeling
nouns = ['temple', 'caljic', 'winkle', 'porte', 'evans', 'griffin', 'idabel', 
        'thf', 'ts', 'tt', 'fl', 'hf', 'yoc', 'yol', 'tn', 'yo', 'tht', 'dondell', 
        'kashmiri', 'mckague', 'leons', 'barnes', 'vanessen', 'cora', 'ps', 'ling', 
        'tsang', 'alice', 'shunling', 'lucy', 'kristine', 'oporto', 'rea', 'prudential', 
        'rojas', 'anita', 'veronicas', 'tillie', 'penny', 'toby', 'noah', 'darin', 'albanesi', 
        'bernet', 'talman', 'cvhsmskl', 'kenny', 'poole', 'shea', 'kevin', 'hatfield', 'grahams', 
        'rabil', 'loflin', 'sikes', 'lj', 'kupsch', 'ronald', 'donovan', 'casey', 'whiteside', 'zoda', 
        'brad', 'amster', 'mindz', 'khan', 'rhoades', 'novis', 'kania', 'dart', 'huntington', 
        'corinna', 'gilman', 'lucio', 'padilla', 'adelaido', 'melissa', 'mariah', 'txsd', 'cv', 
        'prasad', 'toby', 'baylor', 'zamora', 'tanya', 'anita', 'vietnamese', 'nguyen', 'vu', 'vo', 'nelsons', 'tam', 
        'riva', 'freeland', 'rick', 'shannon', 'andriana', 'antoinette', 'larre', 'jenkins', 'lacaze', 'chau', 
        'vu', 'teel', 'catlett', 'brantley', 'valeska', 'jewell', 'samuel', 'edgar', 'tierra', 'cody', 'parrish', 
        'gobble', 'phoenix', 'sammantha', 'cj', 'ammandea', 'judith', 'mckay', 'utah', 'davie', 'katrina', 'rademacher', 
        'spears', 'novis', 'bankowitz', 'bausch', 'beatty', 'margaret', 'wenda', 'quintin', 'whitmore', 'holzknecht', 'qaiser', 
        'sumners', 'alan', 'nixon', 'bruce', 'sumner', 'jacksonville', 'mizrahi', 'reggie', 'carol', 'lincoln', 
        'colinas', 'kerry', 'bruno', 'rollins', 'lucy', 'mt', 'faucette', 'covington', 'asheville', 'princeton', 
        'strickland', 'covingtons', 'carlette', 'kirkland', 'dwight', 'kroger', 'loflin', 'rabil', 'samson', 'qq',
        'norris', 'towery', 'holberg', 'farren', 'brittany', 'ou', 'sp', 'ab', 'blount', 'amarillo', 'gibson', 
        'orlando', 'ellis', 'umhm', 'jaffe', 'currin', 'pender', 'shulenberger', 'franchune', 'epps', 'hutchinson', 
        'milton', 'chavez', 'cherry', 'holden', 'jeanette', 'herb', 'edna', 'sharp', 'sue', 'penny', 'car', 'truck', 'guns', 
        'gillard', 'laura', 'priessler', 'kurt', 'judith', 'sammi', 'matthew', 'davie', 'cj', 'shaniece', 'raydale', 'gayla', 
        'fazio', 'edwards', 'milo', 'seyler', 'shawanna', 'miki', 'hackler', 'galliani', 'springs', 'palm', 'dondell', 'twyla', 
        'cal', 'arivaca', 'wedow', 'tel', 'copley', 'stonex', 'jason', 'gina', 'ivans', 'weinstein', 'montiel', 'weinsteins', 
        'mills', 'belinda', 'armando', 'oscar', 'salcido', 'bryant', 'narines', 'greeley', 'munoz', 'chung', 'thb', 'op', 'tbb', 
        'havb', 'corinna', 'bb', 'hbr', 'yup', 'shb', 'arb', 'christina', 'oregon', 'christinas', 'shaniece', 'jackie', 'kochsiek', 
        'temple', 'cooper', 'celeste', 'yoo', 'koppers', 'ronnie', 'hr', 'robbeloth']

df['transcript_cleaned'] = df['transcript_cleaned'].apply(lambda x: [word for word in x if word not in (nouns)]) ## proper nouns

In [173]:
bertdocs = (df['transcript_cleaned'].apply(lambda x : [x[i:i + 500] for i in range(0, len(x), 500)]))

docs = []
for i in range(len(bertdocs)):
    for j in range(len(bertdocs[i])):
        docs.append(' '.join(bertdocs[i][j]))

In [174]:
topic_model = BERTopic()
topics, probs = topic_model.fit_transform(docs)

topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,3288,-1_house_room_little_home,"[house, room, little, home, police, children, ...",[bob seats marshal merely scenario marshal lit...
1,0,212,0_house_room_money_road,"[house, room, money, road, van, night, little,...",[patel driver expiration daveggios sleep tired...
2,1,181,1_disorder_diagnosis_brain_mental,"[disorder, diagnosis, brain, mental, symptoms,...",[demonstrates histrionics histrionics dramatic...
3,2,113,2_mitigating_aggravating_death_life,"[mitigating, aggravating, death, life, appropr...",[rise seats seats confer enters seats sentence...
4,3,105,3_hospital_medical_doctor_symptoms,"[hospital, medical, doctor, symptoms, seizure,...",[moores plans marry solid spending meals frequ...
...,...,...,...,...,...
74,73,11,73_eler_motions_sichta_messore,"[eler, motions, sichta, messore, oo, plotkin, ...",[wrong openly exchange thoughts ideas stating ...
75,74,11,74_ligon_murder_crime_bracket,"[ligon, murder, crime, bracket, crimes, passio...",[convey purported timeline chronology evidenti...
76,75,11,75_georgia_loi_rodriquez_cini,"[georgia, loi, rodriquez, cini, stalking, asia...",[difficulties recollect memory rodriquez calen...
77,76,10,76_helen_conn_thorpe_rena,"[helen, conn, thorpe, rena, shawnas, carolyn, ...",[operating wave iength nea regret remorse conf...
78,77,10,77_waterford_daughter_granada_camarillo,"[waterford, daughter, granada, camarillo, cost...",[cuttings basket tractor little tractor unique...

In [178]:
for i in range(len(topic_model.get_topic_info()) - 1):
    top = topic_model.get_topic(i)
    print(i)
    print(" '" + top[0][0] + "', " + "'" + top[1][0] + "', " + "'" + top[2][0] + "', " + "'" + top[3][0] + "', " + "'" + top[4][0] + "', " + "'" +
          top[5][0] + "', " + "'" + top[6][0] + "', " + "'" + top[7][0] + "', " + "'" + top[8][0] + "', " + "'" + top[9][0] + "', ")

0
 'house', 'room', 'money', 'road', 'van', 'night', 'little', 'police', 'drive', 'motel',
1
 'disorder', 'diagnosis', 'brain', 'mental', 'symptoms', 'malingering', 'depression', 'antisocial', 'doctor', 'bipolar',
2
 'mitigating', 'aggravating', 'death', 'life', 'appropriate', 'punishment', 'doubt', 'unanimously', 'recommendation', 'argue',
3
 'hospital', 'medical', 'doctor', 'symptoms', 'seizure', 'vision', 'care', 'nausea', 'nurses', 'vomiting',
4
 'battered', 'domestic', 'violence', 'women', 'syndrome', 'woman', 'abuse', 'batterer', 'battering', 'womans',
5
 'wounds', 'injuries', 'wound', 'injury', 'stab', 'skin', 'body', 'blunt', 'doctor', 'force',
6
 'rattan', 'work', 'money', 'employees', 'mawby', 'manager', 'balance', 'worked', 'paid', 'transaction',
7
 'woods', 'becker', 'police', 'juhasz', 'ingram', 'alarm', 'cubicle', 'restaurant', 'brake', 'crime',
8
 'kids', 'children', 'school', 'house', 'home', 'mom', 'sister', 'family', 'mother', 'little',
9
 'blood', 'spatter', 'stain', 'stains', 'projected', 'knife', 'velocity', 'wall', 'drops', 'bloodstain',
10
 'dna', 'swabs', 'stain', 'blood', 'mixture', 'contributor', 'stains', 'minor', 'profiles', 'excluded',
11
 'yfs', 'ff', 'shf', 'ng', 'rf', 'thfy', 'lf', 'ft', 'tiff', 'ls',
12
 'van', 'passenger', 'plastic', 'compartment', 'box', 'cargo', 'rear', 'body', 'carpet', 'seats',
13
 'life', 'death', 'murder', 'doubt', 'aggravating', 'mitigating', 'family', 'guilty', 'cruel', 'kill',
14
 'baby', 'pregnancy', 'pregnant', 'facebook', 'cobb', 'clinic', 'hospital', 'reagans', 'uterus', 'homer',
15
 'fire', 'smoke', 'electrical', 'detector', 'outlet', 'origin', 'damage', 'wire', 'wires', 'outlets',
16
 'jail', 'correctional', 'classification', 'pod', 'disciplinary', 'facility', 'contraband', 'prisons', 'warden', 'female',
17
 'robbery', 'murder', 'kidnapping', 'guilty', 'felony', 'crime', 'burglary', 'aggravated', 'arson', 'aiding',
18
 'misconduct', 'declaration', 'wish', 'mug', 'aggravating', 'doubt', 'lingering', 'affidavit', 'respect', 'motions',
19
 'school', 'parents', 'taiwanese', 'church', 'mom', 'taiwan', 'high', 'kids', 'sister', 'friends',
20
 'death', 'questionnaire', 'life', 'appropriate', 'punishment', 'children', 'childhood', 'murder', 'mitigating', 'parent',
21
 'mother', 'abuse', 'home', 'stepfather', 'sister', 'daughter', 'christa', 'pike', 'child', 'family',
22
 'church', 'bible', 'chaplain', 'pastor', 'life', 'family', 'ministry', 'minister', 'relationship', 'god',
23
 'blood', 'hairs', 'hair', 'fibers', 'stain', 'stains', 'carpet', 'dna', 'wall', 'spatter',
24
 'murder', 'guilty', 'killing', 'robbery', 'malice', 'kill', 'crime', 'felony', 'premeditation', 'human',
25
 'insurance', 'beneficiary', 'ownership', 'company', 'life', 'gerber', 'insured', 'policies', 'owner', 'fuller',
26
 'child', 'ambulance', 'paramedic', 'pulse', 'residence', 'room', 'bed', 'engine', 'fire', 'bedroom',
27
 'gontarek', 'sheryl', 'matthews', 'irene', 'murder', 'beach', 'felony', 'jail', 'josh', 'home',
28
 'bedroom', 'closet', 'residence', 'room', 'kitchen', 'wall', 'couch', 'casing', 'casings', 'refrigerator',
29
 'drugs', 'rachel', 'mom', 'dad', 'house', 'father', 'candlewood', 'thanksgiving', 'mother', 'cruz',
30
 'crime', 'crimes', 'guilty', 'doubt', 'witnesss', 'criminal', 'alleged', 'weight', 'believability', 'mental',
31
 'boy', 'apartment', 'vcr', 'house', 'little', 'reynoso', 'bruises', 'brother', 'kids', 'children',
32
 'methamphetamine', 'addiction', 'drug', 'meth', 'brain', 'influence', 'nanograms', 'drugs', 'addicted', 'hallucinations',
33
 'sexual', 'girl', 'girls', 'young', 'sex', 'kidnapping', 'relationship', 'amanda', 'gun', 'partners',
34
 'trauma', 'abuse', 'child', 'childhood', 'disorder', 'stress', 'mother', 'posttraumatic', 'history', 'brown',
35
 'computer', 'user', 'laptop', 'myspace', 'software', 'folder', 'internet', 'bulletin', 'computers', 'accessed',
36
 'pathology', 'body', 'medical', 'autopsies', 'doctor', 'injuries', 'wound', 'pathologist', 'external', 'death',
37
 'ridge', 'foot', 'impressions', 'inked', 'powder', 'fingers', 'plastic', 'ridges', 'amido', 'black',
38
 'money', 'shona', 'shelly', 'pregnant', 'butch', 'pecan', 'messages', 'linx', 'gender', 'mandy',
39
 'sex', 'sexual', 'relationship', 'intercourse', 'wife', 'sexually', 'romantic', 'doctor', 'saindon', 'communicate',
40
 'fire', 'smoke', 'house', 'fires', 'marshal', 'russellville', 'burned', 'origin', 'electrical', 'hose',
41
 'cartridge', 'fired', 'bullet', 'gun', 'shotgun', 'firearm', 'trigger', 'barrel', 'bullets', 'round',
42
 'alcohol', 'ethyleneglycol', 'blood', 'toxicology', 'glycol', 'ethylene', 'oleander', 'spiehler', 'urine', 'concentration',
43
 'knife', 'knives', 'blood', 'stabbed', 'stabbing', 'blade', 'kitchen', 'halsey', 'sandra', 'autumn',
44
 'child', 'brain', 'injuries', 'hemorrhage', 'injury', 'doctor', 'subdural', 'hematoma', 'trauma', 'shaking',
45
 'child', 'children', 'protective', 'shorthand', 'therapy', 'contamination', 'foster', 'respect', 'childs', 'parents',
46
 'stroke', 'known', 'signatures', 'baseline', 'standards', 'writer', 'exemplars', 'similarities', 'strokes', 'slant',
47
 'torture', 'mayhem', 'murder', 'guilty', 'felony', 'kill', 'pain', 'maim', 'firstdegree', 'crime',
48
 'bullet', 'shot', 'bunk', 'fired', 'gun', 'fragments', 'fragment', 'cylinder', 'sleeve', 'hartnett',
49
 'burn', 'hot', 'burns', 'injury', 'child', 'skin', 'temperature', 'shock', 'injuries', 'infection',
50
 'tribal', 'tribe', 'funk', 'umm', 'tribes', 'council', 'rancheria', 'cedarville', 'housing', 'rurik',
51
 'vollmer', 'hughes', 'metro', 'jail', 'wedge', 'natalie', 'rosanna', 'louisville', 'dogs', 'corrine',
52
 'sister', 'juarez', 'family', 'parents', 'kids', 'ritt', 'interpreter', 'life', 'mother', 'friends',
53
 'azide', 'sodium', 'peak', 'anne', 'newton', 'cyanide', 'milligrams', 'million', 'acid', 'chemical',
54
 'myspace', 'apartment', 'softball', 'relationship', 'rockin', 'night', 'rodeo', 'trailer', 'messages', 'lompoc',
55
 'brown', 'young', 'affirmative', 'thompson', 'library', 'heath', 'comply', 'hon', 'lieutenant', 'gun',
56
 'torture', 'murder', 'guilty', 'mayhem', 'child', 'abuse', 'felony', 'nontarget', 'negligence', 'manslaughter',
57
 'wound', 'bullet', 'gunshot', 'fragments', 'skull', 'wounds', 'lovell', 'image', 'brain', 'fragment',
58
 'ritt', 'therapist', 'tj', 'red', 'child', 'shorthand', 'worker', 'sarinanas', 'raped', 'dispatch',
59
 'neil', 'mac', 'death', 'topics', 'cherie', 'drugs', 'friends', 'feelings', 'gender', 'impartial',
60
 'arsenic', 'butts', 'hair', 'guinn', 'tamer', 'mees', 'million', 'liver', 'body', 'kiser',
61
 'alma', 'wisconsin', 'gross', 'billy', 'charlie', 'shirley', 'kenosha', 'midland', 'judy', 'pennsylvania',
62
 'burn', 'skin', 'tissue', 'injury', 'burns', 'thermal', 'marks', 'body', 'carbon', 'burned',
63
 'hospital', 'father', 'sparrow', 'chapel', 'parsonage', 'church', 'hill', 'alamance', 'paula', 'tamer',
64
 'jail', 'whitney', 'custody', 'bail', 'hernandez', 'module', 'felony', 'segregation', 'plea', 'protective',
65
 'erica', 'sheppard', 'goodhart', 'brown', 'dickerson', 'ramirez', 'bay', 'warnings', 'woldy', 'apartment',
66
 'penetration', 'sexual', 'alleged', 'force', 'unlawful', 'accomplished', 'victim', 'rape', 'copulation', 'crime',
67
 'lockhart', 'plaque', 'taricka', 'unintelligible', 'carnival', 'tronaas', 'buchanan', 'stipulations', 'frutiger', 'fight',
68
 'natalie', 'russell', 'antifreeze', 'children', 'child', 'vollmer', 'baby', 'kids', 'corrine', 'natalies',
69
 'cd', 'cds', 'stutchman', 'dat', 'voices', 'wrestling', 'enhancement', 'recordings', 'enhanced', 'unintelligible',
70
 'battered', 'abuse', 'abuser', 'child', 'abused', 'womans', 'batterer', 'violence', 'syndrome', 'women',
71
 'intestine', 'stomach', 'meal', 'emptying', 'food', 'gastric', 'digestion', 'digested', 'empty', 'article',
72
 'audreanna', 'britnee', 'zimmerman', 'brown', 'mallory', 'gontarek', 'hedrick', 'browns', 'stun', 'kinnard',
73
 'eler', 'motions', 'sichta', 'messore', 'oo', 'plotkin', 'omaha', 'limiting', 'business', 'charts',
74
 'ligon', 'murder', 'crime', 'bracket', 'crimes', 'passion', 'bracketed', 'offense', 'criminal', 'voluntary',
75
 'georgia', 'loi', 'rodriquez', 'cini', 'stalking', 'asia', 'phillipe', 'cumming', 'police', 'aggravated',
76
 'helen', 'conn', 'thorpe', 'rena', 'shawnas', 'carolyn', 'winn', 'deaconess', 'chi', 'worley',
77
 'waterford', 'daughter', 'granada', 'camarillo', 'costco', 'money', 'hills', 'juanita', 'purchases', 'family',

In [ ]:
seeded_topic_model = BERTopic(seed_topic_list=seed_topic_list, top_n_words=20, n_gram_range=(1, 2))
topics, probs = seeded_topic_model.fit_transform(docs)

seeded_topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,3148,-1_house_room_home_little,"[house, room, home, little, police, child, mur...",[extra mile rosa rosa rosa treat parents paren...
1,0,537,0_death_aggravating_mitigating_crime,"[death, aggravating, mitigating, crime, doubt,...",[evaluating credibility witnesss destroy impai...
2,1,404,1_school_home_kids_house,"[school, home, kids, house, mother, children, ...",[felt cool uncle honestly cool uncle young alc...
3,2,127,2_blood_stain_stains_spatter,"[blood, stain, stains, spatter, hair, wall, bl...",[sock white tube sock alley sock sock sock blo...
4,3,121,3_battered_woman_violence_domestic,"[battered, woman, violence, domestic, domestic...",[mother care children acquiesced mother lift a...
...,...,...,...,...,...
62,61,12,61_brain_child_subdural_injuries,"[brain, child, subdural, injuries, hematoma, h...",[child struck doctor belabor pathology patholo...
63,62,12,62_child_child abuse_murder_abuse,"[child, child abuse, murder, abuse, guilty, ma...",[appropriate bracketed language underlying off...
64,63,11,63_death_drugs_feelings death_friends,"[death, drugs, feelings death, friends, topics...",[passing discussions zero impartiality friend ...
65,64,11,64_swabs_stain_blood_semen,"[swabs, stain, blood, semen, kit, carpet, dna,...",[tight skin black leather belt materials swabs...
66,65,11,65_apartment_night_rockin rodeo_rockin,"[apartment, night, rockin rodeo, rockin, rodeo...",[carrying divorce condoms everywhere house pic...

In [181]:
for i in range(len(seeded_topic_model.get_topic_info()) - 1):
    top = seeded_topic_model.get_topic(i)
    print(top[0][0], top[1][0], top[2][0], top[3][0], top[4][0], top[5][0], top[6][0], top[7][0], top[8][0], top[9][0], 
          top[10][0], top[11][0], top[12][0], top[13][0], top[14][0], top[15][0], top[16][0], top[17][0], top[18][0], top[19][0])

death aggravating mitigating crime doubt murder life appropriate guilty crimes argue criminal respect offense alleged language little punishment sorry aggravation
school home kids house mother children mom family sister little child parents daughter brother old live friends high high school father
blood stain stains spatter hair wall blood blood knife projected pillow shorts drops cut velocity tshirt sock bloodstain bloody bed blood spatter
battered woman violence domestic domestic violence women abuse battered woman syndrome battered women batterer battered womans womans womans syndrome battering relationship child abuser abused victim
wounds injuries wound injury skin body stab blunt doctor force burn death blood stab wound chest bruising knife incised brain tissue
jail pod facility correctional custody work classification housing female dorm disciplinary housed contraband little room commissary outside dayroom corrections truth
woods police becker cubicle alarm body ingram crime room patrol work road outside victor restaurant employed sam sorry residence working
ff yfs shf ng rf thfy lf ft ls tiff tl fi thi lt tf ir rn thit ot lr
dna blood stain dna dna mixture swabs contributor minor profiles statistical excluded stains matched presumptive known mitochondrial database contributors billion image
baby pregnancy pregnant cobb hospital clinic facebook reagans birth uterus homer medical paris shona searches placenta hancock youall baby baby little
sex sexual relationship girl young girls wife victim children sexually intercourse life gun age amanda victims crime woman respect mother
bullet fired gun shot cartridge blood firearm bullets weapon residue trigger gunshot gunshot residue barrel trajectory shotgun particles fragment fragments ammunition
passenger box plastic van cargo rear compartment rope trash black duct white bar package carpet kit seats floorboard bags room
fire smoke detector electrical smoke detector outlet damage origin wire wires fire fire heat wall receptacle franco co breaker television room outlets
van gupton house road driving room drove night money drive aleda little police motel freeway hair home trunk dooney suburban
house rachel van handcuffs road room money hit hands police body little white night face blood guy sex paint black
murder death natalie guilty life child children killed kill doubt dead little family police crime mother baby duct kids girl
disorder diagnosis malingering symptoms mmpi mental stress doctor depression traumatic disorders criteria stress disorder psychiatric traumatic stress scales score abuse psychiatry history
hospital medical doctor room vomiting nausea care arsenic home nurses symptoms pain intensive care nausea vomiting intensive surgery food heart condition work
robbery murder kidnapping guilty felony crime burglary aggravated felony murder arson doubt offense aggravated murder death complicity conspiracy robbery kidnapping crimes lonetta committing
death life questionnaire appropriate children death death punishment death appropriate murder death life childhood crime life death mitigating child killed mental family aggravating parent
church bible chaplain pastor family life children home relationship mother god minister jail school ministry father bible studies love brake church church
work worked employees job working manager cards money exits shift employment employee paid hospital cobb personal room sorry plant business
insurance beneficiary life insurance life company ownership pacifier gerber knauss fuller policies insured owner claim insurance company death money premium mom temporary
child room residence paramedic bed ambulance pulse bedroom fire engine bunk children personnel cpr house bunk bed stairs breathing child child paramedics
murder guilty killing malice crime robbery kill guilty murder felony premeditation premeditated human acted aforethought doubt murder guilty malice aforethought felony murder murder murder unlawful
drugs mom house rachel mother father dad home methamphetamine marijuana school van meth sacramento little friends night drug jamie room
brain iq frontal performance lobe eeg memory frontal lobe average functioning scan normal mmpi impairment doctor intelligence brain damage functional hemisphere slowing
methamphetamine drug addiction meth brain influence drugs nanograms addicted addict high amphetamine hallucinations stimulant effects history paranoia sleep methadone influence methamphetamine
pathology body medical doctor injuries autopsies pathologist death wound wounds external gunshot skin coroners injury training bullet gunshot wound medical examiners internal
life family death mother children aggravating pain love sister mitigating friends mom doubt die punishment crime live child cruel home
bedroom room closet residence wall casing kitchen couch casings bed blood dining box trailer bedroom bedroom stains interior dining room carpet shell
husband waterford daughter house juan residence money wife home family bed camarillo granada hills granada night work paul avenue hills connie costco
computer laptop myspace user software folder bulletin internet computers pc accessed allpornoo website newsgroup drive ip desktop log images image
vision tommy stroke blind emersyn trey symptoms optic migraine optic neuritis neuritis medical mri doctor diagnosis clinic sclerosis cobb headaches eye
foot impressions ridge inked fingers plastic amido amido black toe black finger crime known lcv toes powder blood shoes ridges dna
knife knives knife knife blood stabbed stabbing kitchen blade house sandra halsey halsey autumn mud sandra alley stab lie sock little handwritten
trauma child abuse disorder mother stress posttraumatic stress posttraumatic childhood dad children life stress disorder sexual abuse father death history family age sexual
alcohol blood ethyleneglycol blood alcohol body oleander spiehler ethylene glycol glycol ethylene toxicology urine calculations heart blood concentration negative levels serum dilution dillution
fire smoke fire fire house hose russellville smoke detector detector attic room insurance electrical ambulance wall fire marshal shackelford bed firefighter bedroom marshal
lambert nicolas ring husband home alejo hospital work betty duffey phillip crockpot walther house joes surgery worked working donna brother
stroke known baseline signatures standards writer similarities strokes differences slant speed lowercased habits formation doris exemplars garvin known standards ending stroke ending
child children shorthand protective child protective therapy foster respect apartment mother krippel maloney defts parents abuse contamination kids concerned hypothesis sand tray
burn child hot injury burns skin temperature injuries shock subdural burning thirddegree burned blow hematoma degrees wound infection sparing seconddegree
prozac prednisone lupus psychosis medication disorder prescribed effects medications xanax depression mood doctor brain disorders mental diagnosis serotonin drugs medical
young brown brown young brown young affirmative thompson library gun comply heath hon lieutenant versions warren thompson waltons warren redacted goodrich transcription armstrong
money shona pregnant messages mandy gender mom reveal butch pecan baby shelly gender reveal texting cobern codey mandy body stephanie taylors katie
disorder bipolar bipolar disorder mental diagnosis depression mental health vollmer doctor mental disorder health manic malingering symptoms lithium disorders medication mood diagnosed jail
house drugs room motel heroin methamphetamine night bobby inn little money home gun high room room suburban crazy drug woman house house
azide sodium sodium azide peak milligrams million acid blood chemical taste anne computer kilogram anne newton compound newton chemicals detection spike azide sodium
arsenic butts hair tamer guinn million mees body liver tissue kiser normal arsenic body exposure levels concentration dose root embalming poisoning
balance transaction customer deposit holder deposits checking stevenson atm money banking tratner transactions bills expenses bounced cash manager ending ending balance
thorpe rena father married hospital chapel brother marriage carolyn liz chapel hill winn shawnas home mother church relationship dwights dad brieann
dodson speed crack money trailer daley cab driver brandi police man apartment thao drugs cab sean tran princess jail betty fitzmaurice
trailer breezeway house room bedroom kitchen tack tack room corral lattice gate bed police roberts home typewriter braccio screwdriver donna stricken
vollmer hughes metro metro jail jail natalie wedge rosanna corrine buddy rosanna russell dogs frazier children russell quiet room kids scent frame donna
murder mayhem torture felony felony murder kill murder torture guilty maim crime murder mayhem pain murder murder firstdegree firstdegree murder death doubt mayhem mayhem murder felony torture murder
young brown brown gun young brown young ingram shanice daughter papa shotgun house home becker jacobs stephanie truth kirby police library columbus
erica goodhart sheppard brown erica sheppard dickerson ramirez jerry brown brown apartment bay goodhart goodhart police myrna hargis woldy myrna hargis econo econo lodge goodhart brown
wound bullet gunshot gunshot wound fragments skull wounds bullet fragments brain body exit entrance stippling path scalp image gunshot wounds exit wound bone skin
intestine stomach meal food emptying gastric gastric emptying digestion digested article empty spitz spitz fisher death doctor maio stomach intestine food stomach fisher intestine intestine
brain child subdural injuries hematoma hemorrhage injury shaking trauma doctor pediatric burns subdural hematoma baby medical burn frontal scalp frontal lobe force
child child abuse murder abuse guilty mayhem torture felony nontarget felony child offense crime manslaughter injury involuntary manslaughter death bodily murder guilty firstdegree criminal negligence
death drugs feelings death friends topics feelings gender family impartial zanca counseling school personal feelings anaheim cocaine holcomb friends relatives friend children alcohol
swabs stain blood semen kit carpet dna abo stains belt cheek sperm sw presumptive swabs swabs nonsecretor black urine haptoglobin secretor
apartment night rockin rodeo rockin rodeo home guys relationship lucero limo dance drink drinking goal business dillian softball hair game koeppen

In [280]:
df['transcript_cleaned_stemmed'] = df['transcript_cleaned'].apply(lambda x: [PorterStemmer().stem(word) for word in x]) ## stem
df.head()

,id,transcript,transcript_cleaned,transcript_cleaned_stemmed
0,Cynthia Coffman.txt,i 5148 THIS REQUIRES YOU TO KEEP TWO SEPARATE ...,"[requires, keep, two, separate, compartments, ...","[requir, keep, two, separ, compart, brain, spe..."
1,Sammantha Allen.txt,mind during the trial. Form your final opinion...,"[mind, trial, form, final, opinions, opportuni...","[mind, trial, form, final, opinion, opportun, ..."
2,Maureen McDermott.txt,".. ""YOU MAY NOT DISREGARD THE TESTIMONY OF THE...","[may, disregard, greater, number, witnesses, m...","[may, disregard, greater, number, wit, mere, c..."
3,Brittany Holberg.txt,I Case 2:15-cv-00285-Z-BP Document 11-16 Filed...,"[case, document, filed, page, following, proce...","[case, document, file, page, follow, proceed, ..."
4,Tiffany Cole.txt,"MR. MIZRAHI: Counsel. THE COURT: Yes, sir. MR....","[counsel, yes, sir, final, hours, carol, sumne...","[counsel, ye, sir, final, hour, carol, sumner,..."

In [291]:
word2vecdocs = (df['transcript_cleaned_stemmed'].apply(lambda x : [x[i:i + 20] for i in range(0, len(x), 20)]))

docsW2V = []
for i in range(len(word2vecdocs)):
    for j in range(len(word2vecdocs[i])):
        docsW2V.append(word2vecdocs[i][j])

print(len(docsW2V))

512848

In [292]:
w2v = Word2Vec(sentences=docsW2V, vector_size=300, window=5, min_count=1, workers=4)

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

In [293]:
vocab = w2v.wv.index_to_key
print(len(vocab))

19382

In [ ]:
n = 50

topics = ['hypersexualizing', 'pathologizing', 'sexuality', 'gender', 'discrediting', 'immigration', 'poverty', 'addiction', 
          'racial tropes', 'parenting']
for i in range(len(seed_topic_list)):
    print(topics[i])
    #present_words = [word for word in seed_topic_list[i] if word in vocab]
    present_words = [PorterStemmer().stem(word) for word in seed_topic_list[i] if word in vocab]

    counts = []
    for word in present_words:
        counts.append(word + ': ' + str(w2v.wv.get_vecattr(word, 'count')))
    print(counts)
    
    sim = w2v.wv.most_similar(positive=present_words, topn=n)#, restrict_vocab=13000)

    for w in range(n):
        print(sim[w])
    
    print()

hypersexualizing
['flaunt: 10', 'reveal: 547', 'underwear: 266', 'sex: 2124', 'lure: 220', 'flirt: 89', 'affair: 942', 'adult: 1593', 'charm: 76', 'glamour: 5', 'ass: 202', 'bra: 249', 'slut: 33', 'whore: 73', 'bimbo: 1', 'bitch: 266', 'mistress: 13', 'breast: 193', 'skank: 2', 'cougar: 1']
('punk', 0.7064510583877563)
('faceless', 0.6963807344436646)
('despis', 0.6948962211608887)
('lovabl', 0.6927652359008789)
('charismat', 0.6882348656654358)
('gd', 0.6879371404647827)
('grovel', 0.6878761649131775)
('nunneri', 0.6871497631072998)
('crap', 0.6864204406738281)
('bondag', 0.6836066842079163)
('homeboy', 0.6831664443016052)
('hawaiian', 0.6822991371154785)
('scum', 0.6822910308837891)
('gunni', 0.6805440187454224)
('goali', 0.6768472194671631)
('sydney', 0.6767528653144836)
('brazen', 0.675665020942688)
('wannab', 0.6714948415756226)
('unspoken', 0.6707366108894348)
('unsophist', 0.6665018200874329)
('nanni', 0.6651691198348999)
('misfit', 0.6643394827842712)
('sheep', 0.6609572768211365)
('unattract', 0.659532368183136)
('skater', 0.6594035625457764)
('fondl', 0.6588323712348938)
('wren', 0.6568936109542847)
('unhesitatingli', 0.6560050845146179)
('mamma', 0.6558642983436584)
('loner', 0.6553534269332886)
('tussl', 0.6553183794021606)
('castrat', 0.6553019881248474)
('trashi', 0.655173659324646)
('extrovert', 0.6541786789894104)
('tia', 0.6539992094039917)
('fierc', 0.6532952785491943)
('nerd', 0.6531127095222473)
('creepi', 0.6524778604507446)
('karaok', 0.6516467332839966)
('rejoic', 0.6514004468917847)
('incub', 0.6510661840438843)
('bud', 0.6501497626304626)
('overcoat', 0.6494190692901611)
('orneri', 0.6489617228507996)
('icki', 0.6488056778907776)
('unlucki', 0.6484837532043457)
('grownup', 0.6466960310935974)
('berat', 0.645183265209198)
('unbuckl', 0.645086944103241)
('pulp', 0.6445701122283936)

pathologizing
['cold: 810', 'inhuman: 42', 'scheme: 390', 'fake: 1096', 'liar: 407', 'maling: 624', 'lie: 6025', 'bitch: 266']
('deceit', 0.6902124881744385)
('thief', 0.6365708112716675)
('cheat', 0.5914786458015442)
('exagger', 0.5816752314567566)
('sin', 0.5765912532806396)
('despic', 0.5756545662879944)
('evil', 0.5746217966079712)
('idiot', 0.5668402314186096)
('ugli', 0.5657501816749573)
('pathet', 0.5639771819114685)
('pretend', 0.5621063709259033)
('outrag', 0.5621051788330078)
('stupid', 0.553693950176239)
('feign', 0.5529391169548035)
('con', 0.5517038106918335)
('deceiv', 0.5430433750152588)
('vile', 0.541420578956604)
('decept', 0.5408363938331604)
('clever', 0.5392341613769531)
('monster', 0.5381560325622559)
('wantonli', 0.5381354689598083)
('conniv', 0.5344282984733582)
('selfish', 0.5317416191101074)
('abomin', 0.5311108231544495)
('manipul', 0.5309287309646606)
('crap', 0.5305866003036499)
('outright', 0.5297862887382507)
('dishonest', 0.5237343907356262)
('gullibl', 0.5213085412979126)
('cun', 0.5208554267883301)
('dupe', 0.5200619101524353)
('habitu', 0.5151853561401367)
('repugn', 0.5147824883460999)
('bullshit', 0.5105348229408264)
('concoct', 0.5048619508743286)
('reveng', 0.5045710206031799)
('betray', 0.4989985525608063)
('tomb', 0.4977129101753235)
('wick', 0.49710145592689514)
('callou', 0.49565014243125916)
('reprehens', 0.49561500549316406)
('altruist', 0.49541428685188293)
('evas', 0.4939758777618408)
('unhesitatingli', 0.49388930201530457)
('phoni', 0.49206051230430603)
('immor', 0.4918021559715271)
('narciss', 0.4914848208427429)
('slut', 0.49060770869255066)
('stark', 0.49039098620414734)
('despis', 0.488720566034317)

sexuality
['bitch: 266', 'dyke: 5', 'butch: 88', 'lesbian: 19', 'gay: 370']
('mafia', 0.7308521866798401)
('slut', 0.68443363904953)
('graci', 0.6662101745605469)
('nunneri', 0.6521556377410889)
('despis', 0.6506982445716858)
('teas', 0.6425744891166687)
('preacher', 0.6396359801292419)
('millionair', 0.6373598575592041)
('tia', 0.6360599398612976)
('heiress', 0.6319661736488342)
('lover', 0.6301605105400085)
('gd', 0.6300505995750427)
('dido', 0.6295515298843384)
('unfaith', 0.629336416721344)
('bullshit', 0.6261005401611328)
('slander', 0.6237329840660095)
('orneri', 0.622219979763031)
('loner', 0.6220864653587341)
('mexican', 0.622066080570221)
('cheat', 0.620851457118988)
('pathet', 0.619880199432373)
('whore', 0.6189180016517639)
('taunt', 0.6184227466583252)
('punk', 0.6184038519859314)
('spud', 0.6179461479187012)
('momma', 0.61668461561203)
('hillbilli', 0.6160067915916443)
('tanner', 0.6152111291885376)
('wannab', 0.6141769886016846)
('panther', 0.6137973070144653)
('cancun', 0.6115255355834961)
('unhesitatingli', 0.6103752851486206)
('unspoken', 0.6097556948661804)
('beater', 0.6088035702705383)
('bye', 0.607446014881134)
('hawaiian', 0.6045239567756653)
('faceless', 0.6044607758522034)
('jenni', 0.6039754748344421)
('bisexu', 0.6036995053291321)
('scum', 0.6031776070594788)
('ivori', 0.6008263230323792)
('idiot', 0.6008185744285583)
('grovel', 0.6000540256500244)
('dissatisfi', 0.5990332961082458)
('saga', 0.5986855626106262)
('berat', 0.5982000827789307)
('racist', 0.5979113578796387)
('hardwork', 0.5970029234886169)
('emmi', 0.5969863533973694)
('exuber', 0.5962318181991577)

gender
['virgin: 24', 'pure: 321', 'cold: 810', 'neglect: 460', 'selfish: 92', 'violent: 1609', 'wife: 3665', 'woman: 6484']
('humili', 0.6537885665893555)
('infidel', 0.6501179933547974)
('brutal', 0.6399728059768677)
('callou', 0.6351602673530579)
('viciou', 0.6262437105178833)
('terror', 0.6225461363792419)
('savag', 0.6190921068191528)
('uncar', 0.6113300323486328)
('provok', 0.6075319647789001)
('endur', 0.6041024923324585)
('despic', 0.5987756848335266)
('immatur', 0.5979641675949097)
('prey', 0.59593266248703)
('disgust', 0.5918653011322021)
('unwant', 0.5869998335838318)
('predat', 0.5851825475692749)
('vulner', 0.582243800163269)
('vile', 0.5795094966888428)
('lust', 0.5786252021789551)
('terrifi', 0.5784820318222046)
('monster', 0.5771061182022095)
('mistreat', 0.5763099789619446)
('brazen', 0.5762348771095276)
('outrag', 0.5743216872215271)
('evil', 0.5719692707061768)
('volatil', 0.5678372979164124)
('badli', 0.5668802857398987)
('faceless', 0.5666712522506714)
('betray', 0.5663734078407288)
('unfaith', 0.5602725744247437)
('maniac', 0.5599095821380615)
('vicious', 0.5589412450790405)
('thrill', 0.5581823587417603)
('temper', 0.5580870509147644)
('cruelli', 0.5554578900337219)
('wantonli', 0.5528194308280945)
('repuls', 0.5519101619720459)
('slay', 0.5494886040687561)
('despis', 0.5483842492103577)
('horrif', 0.5477515459060669)
('obedi', 0.5476241111755371)
('senseless', 0.547278642654419)
('devast', 0.5472486019134521)
('shockingli', 0.5465885996818542)
('teas', 0.5461588501930237)
('asham', 0.5461181998252869)
('motherhood', 0.5461085438728333)
('wive', 0.5451030731201172)
('jealou', 0.544931173324585)
('greed', 0.5446141958236694)

discrediting
['liar: 407', 'lie: 6025']
('deceit', 0.6001161336898804)
('cheat', 0.5453225374221802)
('deceiv', 0.5197487473487854)
('exagger', 0.5088034868240356)
('untruth', 0.49963387846946716)
('manipul', 0.4903883635997772)
('outright', 0.475667268037796)
('pretend', 0.4749509394168854)
('stori', 0.4687740206718445)
('untru', 0.4685908854007721)
('thief', 0.46537208557128906)
('habitu', 0.4648182690143585)
('confront', 0.45940524339675903)
('afraid', 0.4459485113620758)
('evas', 0.4423106014728546)
('fool', 0.4393645226955414)
('dishonest', 0.438177227973938)
('maling', 0.43666625022888184)
('verac', 0.43612220883369446)
('stupid', 0.4353370666503906)
('accus', 0.43367427587509155)
('ridicul', 0.4324866831302643)
('blame', 0.43155112862586975)
('decept', 0.43114644289016724)
('fault', 0.4150274097919464)
('convincingli', 0.41323184967041016)
('honest', 0.41136521100997925)
('bitch', 0.4094134271144867)
('concoct', 0.4075991213321686)
('contradict', 0.40643930435180664)
('gay', 0.40423813462257385)
('fake', 0.40386763215065)
('honesti', 0.40214669704437256)
('truth', 0.4010499119758606)
('confess', 0.39702555537223816)
('brag', 0.39476853609085083)
('bacca', 0.3943721652030945)
('misrepres', 0.39409229159355164)
('reput', 0.3929440379142761)
('true', 0.39292073249816895)
('recant', 0.39150315523147583)
('wow', 0.38849717378616333)
('ass', 0.38842999935150146)
('absurd', 0.3877626657485962)
('ugli', 0.38741323351860046)
('perjur', 0.38739460706710815)
('crazi', 0.38636425137519836)
('motiv', 0.385165274143219)
('betray', 0.38503170013427734)
('devil', 0.3847125470638275)

immigration
['alien: 69', 'foreign: 280', 'backward: 254', 'citizenship: 22', 'wetback: 3', 'ethnic: 124', 'accent: 59', 'english: 561', 'custom: 817', 'steal: 686', 'border: 285', 'home: 14670']
('anteced', 0.680682361125946)
('brazil', 0.6759547591209412)
('korean', 0.667566180229187)
('lutheran', 0.6612598299980164)
('competitor', 0.6558555364608765)
('embassi', 0.6451042890548706)
('chariti', 0.6381334066390991)
('saigon', 0.6377660036087036)
('trader', 0.6374564170837402)
('clientel', 0.6369050145149231)
('tiro', 0.6357505917549133)
('evangel', 0.6345627307891846)
('poland', 0.6336081027984619)
('grovel', 0.6317640542984009)
('sweden', 0.6317113637924194)
('bookstor', 0.6313918232917786)
('dune', 0.6313257217407227)
('stereotyp', 0.6301090121269226)
('mexican', 0.6294029355049133)
('hum', 0.6290764212608337)
('nun', 0.6286132335662842)
('taillight', 0.62691330909729)
('boomer', 0.6265801191329956)
('fresno', 0.6265048980712891)
('germani', 0.6261450052261353)
('ottawa', 0.6248489618301392)
('northeastern', 0.6228734850883484)
('subcultur', 0.62245112657547)
('taxicab', 0.6218584775924683)
('skater', 0.621788740158081)
('mormon', 0.6213549971580505)
('european', 0.6209960579872131)
('jenni', 0.6207231283187866)
('mainstream', 0.6180118918418884)
('takeov', 0.6175483465194702)
('rival', 0.6170522570610046)
('unsophist', 0.6159178614616394)
('fratern', 0.6152233481407166)
('northwestern', 0.6147612929344177)
('apach', 0.6141425967216492)
('cola', 0.6139141321182251)
('limonit', 0.613552987575531)
('crummi', 0.6122587323188782)
('southeastern', 0.6121676564216614)
('tourist', 0.6120017766952515)
('nerd', 0.6114798784255981)
('cape', 0.6113414764404297)
('extrovert', 0.6095724105834961)
('hss', 0.6094086170196533)
('iraq', 0.6088497042655945)

poverty
['poor: 607', 'cheap: 72', 'trailer: 2627', 'trash: 1242']
('tractor', 0.6130984425544739)
('hors', 0.6038666367530823)
('barn', 0.5865241885185242)
('garbag', 0.5805862545967102)
('cow', 0.5774815678596497)
('dumpster', 0.569442629814148)
('clutter', 0.5646049976348877)
('ocean', 0.5634863376617432)
('filthi', 0.5586814880371094)
('pack', 0.5565166473388672)
('can', 0.5499025583267212)
('mower', 0.5489271879196167)
('suitcas', 0.5467694997787476)
('rummag', 0.5454925894737244)
('extravag', 0.5451209545135498)
('junk', 0.5400641560554504)
('decor', 0.5358546376228333)
('groceri', 0.5326611995697021)
('loot', 0.5303404331207275)
('saddl', 0.5282221436500549)
('chicken', 0.5270134806632996)
('rv', 0.5261146426200867)
('perfum', 0.5255602598190308)
('hog', 0.5240856409072876)
('merchandis', 0.5216761231422424)
('carton', 0.5199539065361023)
('grass', 0.5196908116340637)
('boat', 0.5191380381584167)
('indianapoli', 0.5174791216850281)
('cement', 0.5174601674079895)
('champion', 0.5143109560012817)
('duck', 0.5124327540397644)
('garden', 0.5121736526489258)
('truck', 0.5102943181991577)
('crowd', 0.5093931555747986)
('mow', 0.5089725255966187)
('knit', 0.5080282092094421)
('trailblaz', 0.5058737397193909)
('ranch', 0.505196750164032)
('nearbi', 0.5042553544044495)
('toy', 0.5032757520675659)
('tuna', 0.5029573440551758)
('jet', 0.5029011964797974)
('pot', 0.5022636651992798)
('bird', 0.5013955235481262)
('rotisseri', 0.5002126693725586)
('brazen', 0.4994161128997803)
('alleyway', 0.4986593723297119)
('dell', 0.4979821443557739)
('unclean', 0.4979728162288666)

addiction
['speed: 861', 'marijuana: 699', 'heroin: 361', 'addict: 929']
('cocain', 0.8229135870933533)
('meth', 0.8014686703681946)
('methamphetamin', 0.7958378791809082)
('drug', 0.7340603470802307)
('snort', 0.7213258147239685)
('lsd', 0.7007256746292114)
('crank', 0.698063313961029)
('downer', 0.6863614916801453)
('bing', 0.6855509877204895)
('supplier', 0.6825447678565979)
('usag', 0.6793376207351685)
('caffein', 0.6682471632957458)
('bong', 0.6606053113937378)
('crack', 0.6514192223548889)
('coke', 0.6453672647476196)
('amphetamin', 0.6402247548103333)
('pcp', 0.6370229721069336)
('drank', 0.6364487409591675)
('weed', 0.6338777542114258)
('barbitur', 0.628165066242218)
('dealer', 0.625421941280365)
('paraphernalia', 0.6230138540267944)
('benzodiazepin', 0.6215104460716248)
('opiat', 0.6209478974342346)
('hepat', 0.6089410781860352)
('drinker', 0.6069725155830383)
('demerol', 0.6033633351325989)
('alcohol', 0.6024938821792603)
('stimul', 0.5984466671943665)
('dope', 0.5979899764060974)
('tequila', 0.5928215980529785)
('valium', 0.5895048975944519)
('morphin', 0.5857159495353699)
('tranquil', 0.5793210864067078)
('whiskey', 0.5784698724746704)
('diet', 0.575210452079773)
('drink', 0.5696775913238525)
('pimp', 0.5651218295097351)
('nicotin', 0.5643828511238098)
('ingest', 0.5640307664871216)
('thc', 0.5637891888618469)
('phenergan', 0.557930588722229)
('prescript', 0.5532486438751221)
('wean', 0.5499304533004761)
('puff', 0.5484102964401245)
('beverag', 0.547882616519928)
('fiend', 0.5471795797348022)
('tweak', 0.5455895066261292)
('robitussin', 0.5432090759277344)
('narcot', 0.5402554869651794)

racial tropes
['negro: 2', 'feral: 2', 'brute: 15', 'gang: 679', 'thug: 26', 'ethnic: 124']
('dropout', 0.7998515963554382)
('grovel', 0.7904471755027771)
('saigon', 0.7755743265151978)
('devalu', 0.7683759927749634)
('skater', 0.7659194469451904)
('insensit', 0.7635880708694458)
('extrovert', 0.7630789279937744)
('faceless', 0.7599749565124512)
('puf', 0.7591686248779297)
('boomer', 0.7590993642807007)
('rival', 0.7584016919136047)
('unsophist', 0.7556846141815186)
('taillight', 0.754902184009552)
('unspoken', 0.7540354132652283)
('hilli', 0.753785252571106)
('discipl', 0.7536967396736145)
('psa', 0.7527967095375061)
('elisa', 0.752116858959198)
('nich', 0.7502754926681519)
('slaveri', 0.7490096688270569)
('kinder', 0.7489787936210632)
('jenni', 0.748204231262207)
('nerd', 0.7478070855140686)
('blower', 0.7469170093536377)
('cola', 0.7468832731246948)
('charismat', 0.746844470500946)
('carat', 0.7466479539871216)
('predilect', 0.7444006204605103)
('hurl', 0.7434157133102417)
('haze', 0.7425940632820129)
('demo', 0.7400562167167664)
('hungari', 0.7400208115577698)
('counterpart', 0.7397230863571167)
('strangest', 0.7397170662879944)
('sweden', 0.7391055226325989)
('backbon', 0.7378433346748352)
('silo', 0.7373455166816711)
('russia', 0.7365501523017883)
('clash', 0.7361738085746765)
('midwestern', 0.7357092499732971)
('doom', 0.7356263995170593)
('flirtat', 0.733978807926178)
('anteced', 0.7337029576301575)
('innat', 0.7332792282104492)
('castig', 0.7330742478370667)
('troth', 0.7314835786819458)
('stereotyp', 0.7314816117286682)
('peckerwood', 0.7304088473320007)
('ecolog', 0.7303157448768616)
('epithet', 0.7302221655845642)

parenting
['child: 12389', 'neglect: 460', 'mom: 5677', 'mother: 10457', 'matriarch: 29', 'dad: 2662', 'father: 4556', 'patriarch: 3']
('sibl', 0.7093818187713623)
('stepfath', 0.708059549331665)
('grandpar', 0.7049232125282288)
('stepmoth', 0.6875616312026978)
('grandmoth', 0.6813094019889832)
('patern', 0.6625633835792542)
('granddaught', 0.655937135219574)
('parent', 0.654430627822876)
('grandma', 0.6454154849052429)
('estrang', 0.6344038248062134)
('stepdaught', 0.6312500834465027)
('mama', 0.6189770698547363)
('daddi', 0.6128144860267639)
('nurtur', 0.6091125011444092)
('grandson', 0.6043232083320618)
('josh', 0.6001794934272766)
('uncl', 0.5946000218391418)
('grandpa', 0.5936886668205261)
('spoil', 0.5918819308280945)
('shun', 0.5887474417686462)
('grew', 0.5878217816352844)
('disown', 0.5863617658615112)
('ador', 0.5854216814041138)
('motherhood', 0.5839940905570984)
('remarri', 0.583317756652832)
('nephew', 0.5793748497962952)
('trey', 0.5756655931472778)
('aunt', 0.5743013024330139)
('brother', 0.5737001299858093)
('boo', 0.5735189914703369)
('elder', 0.5709335207939148)
('disciplinarian', 0.5699044466018677)
('household', 0.5670619010925293)
('grandchild', 0.565303385257721)
('mackenzi', 0.5652607679367065)
('aunti', 0.5631709098815918)
('daughter', 0.5611047148704529)
('firstborn', 0.5603983998298645)
('mistreat', 0.5573193430900574)
('dearli', 0.557141125202179)
('housewif', 0.5557966232299805)
('bray', 0.5553338527679443)
('caretak', 0.5552970767021179)
('chaotic', 0.5545039772987366)
('grandchildren', 0.5543487071990967)
('eldest', 0.5534540414810181)
('grow', 0.5508302450180054)
('torreon', 0.5493804216384888)
('kid', 0.548875629901886)
('resent', 0.5463318228721619)